/*
 * Creature Lab — animal data and name pools.
 *
 * Every animal describes its head, body and covering separately so the generator
 * can splice one animal's head onto the other's body for the image prompt.
 *
 *   pre / suf   word fragments used to build the hybrid's name ("Li" + "ger")
 *   size        1 (pocket-sized) .. 5 (gigantic)
 *   speed       1 (slowpoke) .. 5 (lightning-fast)
 *   fierce      1 (total softie) .. 5 (fearsome)
 *   extras      [part, phrase] pairs; the FIRST one is the animal's signature feature
 *               and is always shown on the hybrid. Two extras never share a part.
 *   powers      fun animal facts shown as the hybrid's superpowers
 *   temper      keys into TEMPERAMENTS
 *   names       classic pet names for this animal
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.CLData = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const GROUPS = {
    mammal: { label: 'Mammals', emoji: '🐾' },
    bird: { label: 'Birds', emoji: '🪶' },
    reptile: { label: 'Reptiles & amphibians', emoji: '🦎' },
    ocean: { label: 'Ocean life', emoji: '🌊' },
    bug: { label: 'Bugs', emoji: '🐛' }
  };

  const HABITATS = {
    savanna: { label: 'Savanna', scene: 'standing on the golden African savanna at sunset with acacia trees behind it', why: 'Made for a savanna wanderer', names: ['Safari', 'Zuri', 'Kito', 'Sahara', 'Serengeti'] },
    rainforest: { label: 'Rainforest', scene: 'in a lush green rainforest with hanging vines and dappled light', why: 'Perfect for a rainforest dweller', names: ['Mango', 'Kiwi', 'Tango', 'Monsoon', 'Vine'] },
    woodland: { label: 'Woodland', scene: 'in a misty woodland clearing with ferns and mossy logs', why: 'A woodsy name for a forest creature', names: ['Hazel', 'Acorn', 'Bramble', 'Fern', 'Maple'] },
    polar: { label: 'Polar ice', scene: 'on sparkling snow and sea ice under a pale blue sky', why: 'A frosty name for a polar creature', names: ['Frosty', 'Blizzard', 'Aurora', 'Igloo', 'Snowflake'] },
    ocean: { label: 'Ocean', scene: 'swimming in clear turquoise ocean water with sunbeams streaming down', why: 'Perfect for an ocean explorer', names: ['Bubbles', 'Coral', 'Neptune', 'Marina', 'Tide'] },
    desert: { label: 'Desert', scene: 'among rippling sand dunes in a sunlit desert', why: 'A sun-baked name for a desert dweller', names: ['Dune', 'Cactus', 'Oasis', 'Mirage', 'Sandy'] },
    farm: { label: 'Farmyard', scene: 'in a sunny farmyard with a red barn in the background', why: 'A down-home name for a farmyard friend', names: ['Clover', 'Daisy', 'Barnaby', 'Haystack', 'Buttercup'] },
    mountains: { label: 'Mountains', scene: 'on a rocky mountain ledge with snowy peaks behind it', why: 'A lofty name for a mountain climber', names: ['Summit', 'Everest', 'Alpine', 'Ridge', 'Boulder'] },
    wetlands: { label: 'Rivers & swamps', scene: 'at the edge of a calm river surrounded by tall reeds', why: 'A splashy name for a river dweller', names: ['Willow', 'Brook', 'Reed', 'Bayou', 'Puddles'] },
    grasslands: { label: 'Grasslands', scene: 'in a wide grassy meadow under a big open sky', why: 'A breezy name for a meadow roamer', names: ['Prairie', 'Meadow', 'Sage', 'Breeze', 'Dusty'] },
    outback: { label: 'Outback', scene: 'in the Australian outback with red earth and eucalyptus trees', why: 'A true-blue name from the outback', names: ['Banjo', 'Matilda', 'Ozzie', 'Wattle', 'Bindi'] },
    home: { label: 'Cozy homes', scene: 'in a cozy, sunlit living room', why: 'A cozy name for a house pet', names: ['Biscuit', 'Muffin', 'Cookie', 'Pickles', 'Waffles'] },
    garden: { label: 'Gardens', scene: 'in a colorful flower garden, macro close-up', why: 'A blooming name for a garden critter', names: ['Petal', 'Poppy', 'Blossom', 'Sprout', 'Tulip'] }
  };

  const DIETS = {
    carnivore: 'Meat-eater',
    herbivore: 'Plant-eater',
    omnivore: 'Eats everything',
    insectivore: 'Bug-muncher'
  };

  const TEMPERAMENTS = {
    brave: { adj: 'brave', names: ['Valor', 'Hero', 'Blaze', 'Maverick', 'Captain'] },
    majestic: { adj: 'majestic', names: ['Majesty', 'Duchess', 'Sir Reginald', 'Baron', 'Empress'] },
    fierce: { adj: 'fierce', names: ['Fury', 'Brutus', 'Thunder', 'Havoc', 'Diesel'] },
    sneaky: { adj: 'sneaky', names: ['Ninja', 'Shadow', 'Whisper', 'Stealth', 'Phantom'] },
    independent: { adj: 'independent', names: ['Indie', 'Nomad', 'Solo', 'Rogue', 'Ranger'] },
    speedy: { adj: 'speedy', names: ['Zoom', 'Rocket', 'Turbo', 'Bolt', 'Zippy'] },
    shy: { adj: 'shy', names: ['Peekaboo', 'Bashful', 'Hush', 'Mouse', 'Blush'] },
    gentle: { adj: 'gentle', names: ['Angel', 'Teddy', 'Dove', 'Honey', 'Sunny'] },
    smart: { adj: 'clever', names: ['Einstein', 'Newton', 'Ada', 'Darwin', 'Professor'] },
    curious: { adj: 'curious', names: ['Scout', 'Columbus', 'Nosey', 'Explorer', 'Sherlock'] },
    social: { adj: 'friendly', names: ['Buddy', 'Pal', 'Chum', 'Sunny', 'Party'] },
    feisty: { adj: 'feisty', names: ['Spitfire', 'Pepper', 'Firecracker', 'Sassafras', 'Tabasco'] },
    loyal: { adj: 'loyal', names: ['Ace', 'Faithful', 'Sidekick', 'Guardian', 'Buddy'] },
    grumpy: { adj: 'grumpy', names: ['Grumbles', 'Crabby', 'Mr. Grumps', 'Stormy', 'Gruff'] },
    playful: { adj: 'playful', names: ['Scamp', 'Bingo', 'Rascal', 'Jingles', 'Pogo'] },
    sleepy: { adj: 'sleepy', names: ['Snooze', 'Dozer', 'Pillow', 'Nap', 'Dreamy'] },
    goofy: { adj: 'goofy', names: ['Goober', 'Noodle', 'Wobbles', 'Doofus', 'Giggles'] },
    calm: { adj: 'laid-back', names: ['Zen', 'Chill', 'Mellow', 'Breezy', 'Sunday'] },
    sassy: { adj: 'sassy', names: ['Diva', 'Sass', 'Queenie', 'Drama', 'Glitz'] },
    mischievous: { adj: 'mischievous', names: ['Loki', 'Gremlin', 'Bandit', 'Mischief', 'Trouble'] },
    chatty: { adj: 'chatty', names: ['Chatterbox', 'Echo', 'Gabby', 'Jabber', 'Opera'] },
    dreamy: { adj: 'dreamy', names: ['Stardust', 'Moonbeam', 'Wish', 'Nova', 'Daydream'] }
  };

  const SIZES = {
    labels: ['Pocket-sized', 'Small', 'Medium', 'Large', 'Gigantic'],
    words: ['pocket-sized', 'small', 'medium-sized', 'large', 'gigantic'],
    phrases: ['tiny, about the size of a hand', 'small', 'medium-sized', 'large', 'gigantic, towering'],
    why: [
      'A tiny name for a pocket-sized creature',
      'A sweet name for a small creature',
      'A trusty name for a medium-sized creature',
      'A big name for a big creature',
      'A mighty name for a gigantic creature'
    ],
    names: [
      ['Peanut', 'Pip', 'Nibbles', 'Button', 'Jellybean'],
      ['Pixel', 'Sprout', 'Widget', 'Scout', 'Biscuit'],
      ['Milo', 'Ziggy', 'Juniper', 'Ollie', 'Rascal'],
      ['Atlas', 'Bruno', 'Tank', 'Juno', 'Hercules'],
      ['Goliath', 'Colossus', 'Behemoth', 'Titan', 'Mammoth']
    ]
  };

  const SPEED_LABELS = ['Slowpoke', 'Leisurely', 'Nimble', 'Speedy', 'Lightning-fast'];
  const FIERCE_LABELS = ['Total softie', 'Gentle', 'Feisty', 'Fierce', 'Fearsome'];
  const FIERCE_WORDS = ['cuddly', 'gentle', 'feisty', 'fierce', 'fearsome'];

  const ANIMALS = [
    // ---------- mammals ----------
    { id: 'lion', name: 'Lion', emoji: '🦁', group: 'mammal', habitat: 'savanna', diet: 'carnivore', food: 'steak', sound: 'Roar',
      size: 4, speed: 4, fierce: 5, pre: ['Li', 'Lio'], suf: ['on', 'ion'],
      head: 'the head of a lion with amber eyes and a broad nose', body: 'the powerful, tawny body of a lion', covering: 'short tawny-gold fur',
      extras: [['mane', 'a huge shaggy golden mane'], ['tail', 'a long tail ending in a dark tuft'], ['feet', 'big padded paws']],
      powers: ['A roar you can hear from 8 km away', 'Napping up to 20 hours a day'], temper: ['brave', 'majestic'], names: ['Leo', 'Rory', 'Kingston'] },
    { id: 'tiger', name: 'Tiger', emoji: '🐯', group: 'mammal', habitat: 'rainforest', diet: 'carnivore', food: 'venison', sound: 'Growl',
      size: 5, speed: 4, fierce: 5, pre: ['Ti', 'Tig'], suf: ['ger', 'iger'],
      head: 'the head of a tiger with white cheek ruffs and golden eyes', body: 'the long, muscular body of a tiger', covering: 'thick orange fur with a white belly',
      extras: [['pattern', 'bold black tiger stripes'], ['tail', 'a long ringed tail'], ['feet', 'huge paws with retractable claws']],
      powers: ['Stripes as unique as a fingerprint', 'Loves a good swim'], temper: ['fierce', 'sneaky'], names: ['Stripes', 'Rajah', 'Saffron'] },
    { id: 'leopard', name: 'Leopard', emoji: '🐆', group: 'mammal', habitat: 'savanna', diet: 'carnivore', food: 'antelope', sound: 'Snarl',
      size: 4, speed: 4, fierce: 4, pre: ['Leo', 'Leop'], suf: ['pard', 'opard'],
      head: 'the head of a leopard with piercing green-gold eyes', body: 'the sleek, muscular body of a leopard', covering: 'short golden fur',
      extras: [['pattern', 'black rosette spots'], ['tail', 'a long spotted tail'], ['feet', 'silent padded paws']],
      powers: ['Hauling dinner up into trees', 'Near-invisible camouflage'], temper: ['sneaky', 'independent'], names: ['Rosie', 'Shadow', 'Jinx'] },
    { id: 'cheetah', name: 'Cheetah', emoji: '🐆', group: 'mammal', habitat: 'savanna', diet: 'carnivore', food: 'gazelle', sound: 'Chirp',
      size: 4, speed: 5, fierce: 3, pre: ['Chee', 'Cheet'], suf: ['etah', 'tah'],
      head: 'the small, rounded head of a cheetah with black tear-line markings', body: 'the lean, long-legged body of a cheetah', covering: 'short golden fur',
      extras: [['pattern', 'solid black spots'], ['legs', 'long, slender sprinter legs'], ['tail', 'a long tail with black rings']],
      powers: ['0 to 95 km/h in three seconds', 'A tail that steers like a rudder'], temper: ['speedy', 'shy'], names: ['Dash', 'Flash', 'Blitz'] },
    { id: 'elephant', name: 'Elephant', emoji: '🐘', group: 'mammal', habitat: 'savanna', diet: 'herbivore', food: 'watermelons', sound: 'Trumpet',
      size: 5, speed: 2, fierce: 3, pre: ['Ele', 'Eleph'], suf: ['phant', 'ephant'],
      head: 'the head of an elephant with huge flapping ears', body: 'the massive, wrinkly body of an elephant', covering: 'thick, wrinkly grey skin',
      extras: [['trunk', 'a long, wrinkly trunk'], ['tusks', 'curved ivory tusks'], ['legs', 'thick, pillar-like legs']],
      powers: ['A memory that never forgets a face', 'A trunk strong enough to lift a log'], temper: ['gentle', 'smart'], names: ['Peanut', 'Trunkles', 'Ellie'] },
    { id: 'giraffe', name: 'Giraffe', emoji: '🦒', group: 'mammal', habitat: 'savanna', diet: 'herbivore', food: 'acacia leaves', sound: 'Hum',
      size: 5, speed: 3, fierce: 2, pre: ['Gira', 'Gir'], suf: ['raffe', 'affe'],
      head: 'the head of a giraffe with little furry horns and long eyelashes', body: 'the tall, sloping body of a giraffe', covering: 'short tan fur',
      extras: [['neck', 'an incredibly long neck'], ['pattern', 'a patchwork of brown spots'], ['tongue', 'a long purple tongue']],
      powers: ['Seeing over the treetops', 'A tongue half a metre long'], temper: ['gentle', 'curious'], names: ['Stretch', 'Twiga', 'Skyler'] },
    { id: 'zebra', name: 'Zebra', emoji: '🦓', group: 'mammal', habitat: 'savanna', diet: 'herbivore', food: 'grass', sound: 'Yip',
      size: 3, speed: 4, fierce: 2, pre: ['Ze', 'Zeb'], suf: ['bra', 'ebra'],
      head: 'the head of a zebra with dark soulful eyes', body: 'the sturdy, horse-like body of a zebra', covering: 'short white fur',
      extras: [['pattern', 'bold black-and-white stripes'], ['mane', 'a short, spiky striped mane'], ['tail', 'a tufted tail']],
      powers: ['Dazzling predators with its stripes', 'A kick that keeps lions away'], temper: ['social', 'feisty'], names: ['Ziggy', 'Domino', 'Zara'] },
    { id: 'horse', name: 'Horse', emoji: '🐴', group: 'mammal', habitat: 'grasslands', diet: 'herbivore', food: 'carrots', sound: 'Neigh',
      size: 4, speed: 5, fierce: 2, pre: ['Hor', 'Horse'], suf: ['orse', 'rse'],
      head: 'the long, elegant head of a horse', body: 'the strong, athletic body of a horse', covering: 'a glossy chestnut coat',
      extras: [['mane', 'a long, flowing mane'], ['legs', 'long legs with sturdy hooves'], ['tail', 'a long, silky tail']],
      powers: ['Galloping at 70 km/h', 'Sleeping standing up'], temper: ['loyal', 'speedy'], names: ['Maverick', 'Spirit', 'Chestnut'] },
    { id: 'donkey', name: 'Donkey', emoji: '🫏', group: 'mammal', habitat: 'farm', diet: 'herbivore', food: 'hay', sound: 'Hee-haw',
      size: 3, speed: 3, fierce: 2, pre: ['Don', 'Donk'], suf: ['onkey', 'key'],
      head: 'the head of a donkey with a soft white muzzle', body: 'the sturdy body of a donkey', covering: 'fuzzy grey-brown fur',
      extras: [['ears', 'enormous long ears'], ['mane', 'a short, stubby mane'], ['legs', 'sturdy legs with small hooves']],
      powers: ['A bray you can hear across the valley', 'Legendary stubbornness'], temper: ['loyal', 'grumpy'], names: ['Jenny', 'Pancho', 'Hazel'] },
    { id: 'gorilla', name: 'Gorilla', emoji: '🦍', group: 'mammal', habitat: 'rainforest', diet: 'herbivore', food: 'wild celery', sound: 'Hoo-hoo',
      size: 5, speed: 3, fierce: 4, pre: ['Gori', 'Gor'], suf: ['rilla', 'illa'],
      head: 'the head of a gorilla with a heavy brow and thoughtful brown eyes', body: 'the huge, muscular body of a silverback gorilla', covering: 'thick black fur',
      extras: [['arms', 'enormous muscular arms'], ['back', 'a silver saddle of fur on its back'], ['hands', 'big leathery hands']],
      powers: ['Chest-drumming that echoes through the jungle', 'Building a fresh leafy bed every night'], temper: ['gentle', 'smart'], names: ['Bruno', 'Koko', 'Moja'] },
    { id: 'kangaroo', name: 'Kangaroo', emoji: '🦘', group: 'mammal', habitat: 'outback', diet: 'herbivore', food: 'grass', sound: 'Cluck',
      size: 4, speed: 4, fierce: 3, pre: ['Kanga', 'Kang'], suf: ['garoo', 'roo'],
      head: 'the head of a kangaroo with tall upright ears', body: 'the upright, muscular body of a kangaroo', covering: 'short reddish-brown fur',
      extras: [['legs', 'huge, powerful hind legs for hopping'], ['tail', 'a thick muscular tail'], ['pouch', 'a cozy belly pouch']],
      powers: ['Hopping 8 metres in a single bound', 'A built-in pocket'], temper: ['playful', 'feisty'], names: ['Joey', 'Skippy', 'Boomer'] },
    { id: 'koala', name: 'Koala', emoji: '🐨', group: 'mammal', habitat: 'outback', diet: 'herbivore', food: 'eucalyptus leaves', sound: 'Snore',
      size: 2, speed: 1, fierce: 1, pre: ['Koa', 'Koal'], suf: ['ala', 'oala'],
      head: 'the head of a koala with a big black button nose', body: 'the round, cuddly body of a koala', covering: 'soft grey fur',
      extras: [['ears', 'big, fluffy round ears'], ['hands', 'grippy clawed hands for hugging trees'], ['chest', 'a fluffy white chest']],
      powers: ['Sleeping 20 hours a day', 'Fingerprints almost like a human’s'], temper: ['sleepy', 'gentle'], names: ['Gumnut', 'Snugglepot', 'Kirra'] },
    { id: 'giant-panda', name: 'Giant Panda', emoji: '🐼', group: 'mammal', habitat: 'woodland', diet: 'herbivore', food: 'bamboo', sound: 'Bleat',
      size: 4, speed: 1, fierce: 2, pre: ['Pan', 'Panda'], suf: ['anda', 'da'],
      head: 'the round head of a giant panda with black eye patches', body: 'the chubby body of a giant panda', covering: 'thick black-and-white fur',
      extras: [['ears', 'fuzzy round black ears'], ['arms', 'fluffy black arms'], ['belly', 'a round, well-fed belly']],
      powers: ['Munching bamboo 12 hours a day', 'A secret “thumb” for gripping bamboo'], temper: ['goofy', 'sleepy'], names: ['Bao', 'Bamboo', 'Mochi'] },
    { id: 'polar-bear', name: 'Polar Bear', emoji: '🐻‍❄️', group: 'mammal', habitat: 'polar', diet: 'carnivore', food: 'seal blubber', sound: 'Huff',
      size: 5, speed: 3, fierce: 5, pre: ['Polar', 'Pola'], suf: ['olar', 'bear'],
      head: 'the long, white head of a polar bear with a black nose', body: 'the huge, powerful body of a polar bear', covering: 'thick creamy-white fur',
      extras: [['feet', 'enormous furry paws for walking on ice'], ['ears', 'small rounded ears'], ['tail', 'a stubby little tail']],
      powers: ['Sniffing out a seal 1.5 km away', 'Swimming for days at a time'], temper: ['fierce', 'independent'], names: ['Frost', 'Nanook', 'Blizzard'] },
    { id: 'grizzly-bear', name: 'Grizzly Bear', emoji: '🐻', group: 'mammal', habitat: 'woodland', diet: 'omnivore', food: 'salmon', sound: 'Growl',
      size: 5, speed: 3, fierce: 5, pre: ['Griz', 'Grizz'], suf: ['izzly', 'zzly'],
      head: 'the broad head of a grizzly bear with small round ears', body: 'the massive body of a grizzly bear', covering: 'thick brown fur with silver tips',
      extras: [['back', 'a big muscular shoulder hump'], ['claws', 'long, curved claws'], ['feet', 'huge padded paws']],
      powers: ['Catching salmon mid-air', 'Sleeping through the whole winter'], temper: ['fierce', 'grumpy'], names: ['Bruno', 'Kodiak', 'Honey'] },
    { id: 'wolf', name: 'Wolf', emoji: '🐺', group: 'mammal', habitat: 'woodland', diet: 'carnivore', food: 'venison', sound: 'Howl',
      size: 3, speed: 4, fierce: 4, pre: ['Wol', 'Wolf'], suf: ['olf', 'wolf'],
      head: 'the head of a grey wolf with piercing yellow eyes and a long snout', body: 'the lean, rangy body of a wolf', covering: 'thick grey fur',
      extras: [['tail', 'a big bushy tail'], ['ears', 'pointed upright ears'], ['ruff', 'a shaggy neck ruff']],
      powers: ['A howl that carries for kilometres', 'Unbeatable pack teamwork'], temper: ['loyal', 'fierce'], names: ['Ghost', 'Luna', 'Fang'] },
    { id: 'fox', name: 'Fox', emoji: '🦊', group: 'mammal', habitat: 'woodland', diet: 'omnivore', food: 'berries', sound: 'Yap',
      size: 2, speed: 4, fierce: 2, pre: ['Fox', 'Foxy'], suf: ['ox', 'fox'],
      head: 'the head of a red fox with a pointed snout and amber eyes', body: 'the slender body of a red fox', covering: 'fiery orange fur with a white chest',
      extras: [['tail', 'a big, fluffy white-tipped tail'], ['ears', 'large pointed black-backed ears'], ['feet', 'black stocking feet']],
      powers: ['Hearing a mouse squeak from across a field', 'Diving headfirst into snow to catch dinner'], temper: ['sneaky', 'smart'], names: ['Rusty', 'Ember', 'Vixen'] },
    { id: 'rabbit', name: 'Rabbit', emoji: '🐰', group: 'mammal', habitat: 'grasslands', diet: 'herbivore', food: 'carrots', sound: 'Thump',
      size: 2, speed: 4, fierce: 1, pre: ['Rab', 'Bunny'], suf: ['abbit', 'bunny', 'bit'],
      head: 'the head of a rabbit with a twitchy pink nose and big round eyes', body: 'the round, fluffy body of a rabbit', covering: 'soft, fluffy brown fur',
      extras: [['ears', 'long, floppy bunny ears'], ['tail', 'a fluffy cotton-ball tail'], ['legs', 'powerful hopping back legs']],
      powers: ['Seeing almost all the way around', 'Joyful twisting “binky” jumps'], temper: ['playful', 'shy'], names: ['Clover', 'Hopscotch', 'Bun Bun'] },
    { id: 'hedgehog', name: 'Hedgehog', emoji: '🦔', group: 'mammal', habitat: 'woodland', diet: 'insectivore', food: 'beetles', sound: 'Snuffle',
      size: 1, speed: 2, fierce: 2, pre: ['Hedge', 'Hedgy'], suf: ['hog', 'ehog'],
      head: 'the pointed face of a hedgehog with a tiny black nose and beady eyes', body: 'the small, round body of a hedgehog', covering: 'short brown fur',
      extras: [['spines', 'a coat of thousands of sharp spines'], ['feet', 'tiny pink feet'], ['ears', 'little round ears']],
      powers: ['Rolling into a spiky ball', 'Armour made of 5,000 spines'], temper: ['shy', 'grumpy'], names: ['Spike', 'Prickles', 'Conker'] },
    { id: 'sloth', name: 'Sloth', emoji: '🦥', group: 'mammal', habitat: 'rainforest', diet: 'herbivore', food: 'leaves', sound: 'Eeee',
      size: 2, speed: 1, fierce: 1, pre: ['Slo', 'Sloth'], suf: ['oth', 'loth'],
      head: 'the round, smiling face of a sloth with dark eye stripes', body: 'the shaggy, slow-moving body of a sloth', covering: 'shaggy greenish-brown fur',
      extras: [['claws', 'three long hooked claws on each hand'], ['arms', 'long, dangling arms'], ['algae', 'tiny green algae growing in its fur']],
      powers: ['Holding its breath for 40 minutes', 'Hanging upside down all day'], temper: ['sleepy', 'gentle'], names: ['Snooze', 'Slowpoke', 'Mango'] },
    { id: 'rhinoceros', name: 'Rhino', emoji: '🦏', group: 'mammal', habitat: 'savanna', diet: 'herbivore', food: 'shrubs', sound: 'Snort',
      size: 5, speed: 3, fierce: 5, pre: ['Rhino', 'Rhi'], suf: ['ino', 'hino'],
      head: 'the heavy head of a rhinoceros with small eyes and tube-shaped ears', body: 'the huge, armour-plated body of a rhinoceros', covering: 'thick, grey armour-like skin',
      extras: [['horns', 'two large horns on its snout'], ['legs', 'stumpy tree-trunk legs'], ['tail', 'a short tufted tail']],
      powers: ['Charging at 50 km/h', 'A horn made of the same stuff as fingernails'], temper: ['grumpy', 'brave'], names: ['Tank', 'Rocky', 'Horatio'] },
    { id: 'hippopotamus', name: 'Hippo', emoji: '🦛', group: 'mammal', habitat: 'wetlands', diet: 'herbivore', food: 'grass', sound: 'Grunt',
      size: 5, speed: 3, fierce: 5, pre: ['Hippo', 'Hip'], suf: ['ppo', 'potamus'],
      head: 'the huge head of a hippopotamus with tiny wiggly ears and nostrils on top', body: 'the barrel-shaped body of a hippopotamus', covering: 'smooth, thick pinkish-grey skin',
      extras: [['mouth', 'a gigantic mouth with tusk-like teeth'], ['legs', 'short, stumpy legs'], ['tail', 'a short, flat tail']],
      powers: ['Making its own pink “sunscreen” sweat', 'Holding its breath for 5 minutes'], temper: ['grumpy', 'goofy'], names: ['Hugo', 'Bubbles', 'Wallow'] },
    { id: 'camel', name: 'Camel', emoji: '🐫', group: 'mammal', habitat: 'desert', diet: 'herbivore', food: 'dates', sound: 'Grumble',
      size: 5, speed: 3, fierce: 2, pre: ['Cam', 'Came'], suf: ['amel', 'mel'],
      head: 'the head of a camel with bushy eyelashes and droopy lips', body: 'the tall, lanky body of a camel', covering: 'shaggy, sandy-beige fur',
      extras: [['humps', 'two big humps on its back'], ['legs', 'long, knobbly legs'], ['feet', 'wide padded feet for walking on sand']],
      powers: ['Going a week without water', 'Closing its nostrils in sandstorms'], temper: ['calm', 'grumpy'], names: ['Sahara', 'Lumpy', 'Dune'] },
    { id: 'llama', name: 'Llama', emoji: '🦙', group: 'mammal', habitat: 'mountains', diet: 'herbivore', food: 'grass', sound: 'Hum',
      size: 3, speed: 3, fierce: 2, pre: ['Lla', 'Llam'], suf: ['ama', 'lama'],
      head: 'the head of a llama with tall banana-shaped ears and a goofy expression', body: 'the fluffy, long-necked body of a llama', covering: 'thick, woolly cream fur',
      extras: [['neck', 'a long, fluffy neck'], ['wool', 'a shaggy woolly coat'], ['feet', 'two-toed padded feet']],
      powers: ['Spitting with pinpoint accuracy', 'Carrying heavy packs up mountains'], temper: ['goofy', 'sassy'], names: ['Como', 'Pompom', 'Drama'] },
    { id: 'goat', name: 'Goat', emoji: '🐐', group: 'mammal', habitat: 'mountains', diet: 'herbivore', food: 'weeds', sound: 'Bleat',
      size: 3, speed: 3, fierce: 3, pre: ['Go', 'Goa'], suf: ['oat', 'goat'],
      head: 'the head of a goat with strange rectangular pupils', body: 'the nimble, sturdy body of a goat', covering: 'short white-and-brown hair',
      extras: [['horns', 'curved, ridged horns'], ['beard', 'a scruffy chin beard'], ['feet', 'split hooves for climbing cliffs']],
      powers: ['Climbing near-vertical cliffs', 'Climbing trees to reach tasty leaves'], temper: ['mischievous', 'curious'], names: ['Billy', 'Nanny', 'Gruff'] },
    { id: 'sheep', name: 'Sheep', emoji: '🐑', group: 'mammal', habitat: 'farm', diet: 'herbivore', food: 'clover', sound: 'Baa',
      size: 3, speed: 2, fierce: 1, pre: ['Shee', 'Sheep'], suf: ['eep', 'heep'],
      head: 'the gentle face of a sheep with floppy ears', body: 'the round body of a sheep', covering: 'thick, fluffy white wool',
      extras: [['wool', 'a huge cloud of curly wool'], ['legs', 'skinny black legs'], ['horns', 'small curled horns']],
      powers: ['Growing endless wool', 'Remembering the faces of 50 friends'], temper: ['gentle', 'social'], names: ['Dolly', 'Woolly', 'Fleecy'] },
    { id: 'pig', name: 'Pig', emoji: '🐷', group: 'mammal', habitat: 'farm', diet: 'omnivore', food: 'apples', sound: 'Oink',
      size: 3, speed: 2, fierce: 2, pre: ['Pig', 'Pigg'], suf: ['ig', 'piggy'],
      head: 'the head of a pig with a round pink snout', body: 'the round, pink body of a pig', covering: 'smooth pink skin with fine bristles',
      extras: [['tail', 'a curly corkscrew tail'], ['ears', 'floppy pink ears'], ['feet', 'little trotters']],
      powers: ['Sniffing out buried truffles', 'Rolling in mud to stay cool'], temper: ['smart', 'goofy'], names: ['Wilbur', 'Truffle', 'Hamlet'] },
    { id: 'dog', name: 'Dog', emoji: '🐶', group: 'mammal', habitat: 'home', diet: 'omnivore', food: 'dog biscuits', sound: 'Woof',
      size: 3, speed: 4, fierce: 2, pre: ['Dog', 'Pup'], suf: ['og', 'dog', 'pup'],
      head: 'the friendly head of a golden retriever with a wet black nose', body: 'the sturdy body of a dog', covering: 'soft golden fur',
      extras: [['tail', 'a happily wagging feathery tail'], ['ears', 'soft floppy ears'], ['tongue', 'a lolling pink tongue']],
      powers: ['A nose 10,000 times better than ours', 'Unconditional love'], temper: ['loyal', 'playful'], names: ['Buddy', 'Max', 'Rover'] },
    { id: 'cat', name: 'Cat', emoji: '🐱', group: 'mammal', habitat: 'home', diet: 'carnivore', food: 'tuna', sound: 'Meow',
      size: 2, speed: 4, fierce: 3, pre: ['Cat', 'Kit'], suf: ['at', 'cat', 'kitty'],
      head: 'the head of a ginger tabby cat with bright green eyes', body: 'the sleek, agile body of a cat', covering: 'soft ginger fur',
      extras: [['whiskers', 'long, twitchy whiskers'], ['tail', 'a long, curling tail'], ['ears', 'pointy triangular ears']],
      powers: ['Always landing on its feet', 'A purr like a tiny engine'], temper: ['independent', 'mischievous'], names: ['Whiskers', 'Luna', 'Mittens'] },
    { id: 'moose', name: 'Moose', emoji: '🫎', group: 'mammal', habitat: 'woodland', diet: 'herbivore', food: 'water plants', sound: 'Bellow',
      size: 5, speed: 3, fierce: 4, pre: ['Moo', 'Moos'], suf: ['oose', 'moose'],
      head: 'the long, droopy-nosed head of a moose with a dangling dewlap', body: 'the huge, long-legged body of a moose', covering: 'coarse dark-brown fur',
      extras: [['antlers', 'enormous flat palm-shaped antlers'], ['legs', 'long, stilt-like legs'], ['back', 'a humped shoulder']],
      powers: ['Diving 6 metres underwater for snacks', 'Antlers that regrow every year'], temper: ['calm', 'brave'], names: ['Maple', 'Timber', 'Morris'] },
    { id: 'capybara', name: 'Capybara', emoji: '🐾', group: 'mammal', habitat: 'wetlands', diet: 'herbivore', food: 'water lettuce', sound: 'Purr',
      size: 3, speed: 2, fierce: 1, pre: ['Capy', 'Capyba'], suf: ['bara', 'ybara'],
      head: 'the blunt, boxy head of a capybara with tiny ears high on its head', body: 'the barrel-shaped body of a capybara', covering: 'coarse reddish-brown fur',
      extras: [['vibe', 'a totally unbothered, zen expression'], ['feet', 'slightly webbed feet'], ['legs', 'short, sturdy legs']],
      powers: ['Being friends with literally everyone', 'Napping in hot springs'], temper: ['calm', 'social'], names: ['Chill', 'Potato', 'Cappuccino'] },
    { id: 'bat', name: 'Bat', emoji: '🦇', group: 'mammal', habitat: 'woodland', diet: 'insectivore', food: 'moths', sound: 'Squeak',
      size: 1, speed: 4, fierce: 2, pre: ['Bat', 'Batt'], suf: ['bat', 'at'],
      head: 'the head of a bat with a squashed, leaf-shaped nose and tiny eyes', body: 'the small, furry body of a bat', covering: 'velvety dark-brown fur',
      extras: [['wings', 'large, leathery bat wings'], ['ears', 'enormous pointed ears'], ['feet', 'clawed feet for hanging upside down']],
      powers: ['Echolocation “sonar” hearing', 'Flying in total darkness'], temper: ['sneaky', 'curious'], names: ['Vlad', 'Echo', 'Batty'] },
    { id: 'otter', name: 'Sea Otter', emoji: '🦦', group: 'mammal', habitat: 'ocean', diet: 'carnivore', food: 'shellfish', sound: 'Squeal',
      size: 2, speed: 4, fierce: 2, pre: ['Ot', 'Ott'], suf: ['otter', 'tter'],
      head: 'the round head of a sea otter with bright button eyes', body: 'the long, sleek body of a sea otter', covering: 'thick, glossy brown fur',
      extras: [['whiskers', 'long, sensitive whiskers'], ['feet', 'webbed paws'], ['tail', 'a thick, rudder-like tail']],
      powers: ['Holding hands while it sleeps', 'Using rocks as tools'], temper: ['playful', 'social'], names: ['Pebble', 'Ollie', 'Splash'] },

    // ---------- birds ----------
    { id: 'eagle', name: 'Eagle', emoji: '🦅', group: 'bird', habitat: 'mountains', diet: 'carnivore', food: 'fish', sound: 'Screech',
      size: 3, speed: 5, fierce: 4, pre: ['Ea', 'Eag'], suf: ['agle', 'gle', 'eagle'],
      head: 'the head of a bald eagle with white feathers, a hooked yellow beak and fierce eyes', body: 'the powerful, feathered body of an eagle', covering: 'dark-brown feathers',
      extras: [['wings', 'huge, broad feathered wings'], ['feet', 'sharp yellow talons'], ['tail', 'a fan of white tail feathers']],
      powers: ['Eyesight up to 8 times sharper than ours', 'Soaring for hours without flapping'], temper: ['majestic', 'fierce'], names: ['Talon', 'Liberty', 'Skye'] },
    { id: 'owl', name: 'Owl', emoji: '🦉', group: 'bird', habitat: 'woodland', diet: 'carnivore', food: 'mice', sound: 'Hoot',
      size: 2, speed: 3, fierce: 3, pre: ['Owl', 'Ow'], suf: ['owl', 'wl'],
      head: 'the round, flat face of an owl with huge golden eyes', body: 'the fluffy, feathered body of an owl', covering: 'speckled brown-and-white feathers',
      extras: [['wings', 'soft, silent wings'], ['tufts', 'feathery ear tufts'], ['feet', 'fluffy feathered talons']],
      powers: ['Turning its head 270 degrees', 'Flying completely silently'], temper: ['smart', 'calm'], names: ['Hoot', 'Sage', 'Athena'] },
    { id: 'penguin', name: 'Penguin', emoji: '🐧', group: 'bird', habitat: 'polar', diet: 'carnivore', food: 'fish', sound: 'Honk',
      size: 3, speed: 2, fierce: 2, pre: ['Pen', 'Peng'], suf: ['guin', 'enguin'],
      head: 'the sleek black head of an emperor penguin with golden-orange ear patches', body: 'the plump, upright tuxedo body of a penguin', covering: 'sleek black-and-white feathers',
      extras: [['flippers', 'stiff wing-flippers'], ['feet', 'orange webbed feet'], ['belly', 'a round white belly']],
      powers: ['Diving more than 500 metres deep', 'Tobogganing on its belly'], temper: ['goofy', 'social'], names: ['Tux', 'Waddles', 'Pebbles'] },
    { id: 'flamingo', name: 'Flamingo', emoji: '🦩', group: 'bird', habitat: 'wetlands', diet: 'omnivore', food: 'shrimp', sound: 'Honk',
      size: 3, speed: 3, fierce: 1, pre: ['Flami', 'Flam'], suf: ['mingo', 'ingo'],
      head: 'the head of a flamingo with a bent, black-tipped beak', body: 'the slender, feathered body of a flamingo', covering: 'bright pink feathers',
      extras: [['legs', 'super-long, skinny pink legs'], ['neck', 'a long S-curved neck'], ['wings', 'pink wings with black edges']],
      powers: ['Balancing on one leg for hours', 'Turning pink from the food it eats'], temper: ['sassy', 'social'], names: ['Pinky', 'Flora', 'Mingo'] },
    { id: 'parrot', name: 'Parrot', emoji: '🦜', group: 'bird', habitat: 'rainforest', diet: 'herbivore', food: 'nuts', sound: 'Squawk',
      size: 2, speed: 4, fierce: 2, pre: ['Par', 'Parr'], suf: ['rot', 'arrot'],
      head: 'the head of a scarlet macaw with a big curved beak', body: 'the vivid red, blue and yellow body of a macaw', covering: 'brilliant rainbow feathers',
      extras: [['tail', 'a long, elegant red tail'], ['wings', 'bright blue-and-yellow wings'], ['feet', 'grippy two-forward, two-back toes']],
      powers: ['Talking back', 'Cracking nuts with one bite'], temper: ['chatty', 'playful'], names: ['Polly', 'Kiwi', 'Captain'] },
    { id: 'toucan', name: 'Toucan', emoji: '🐦', group: 'bird', habitat: 'rainforest', diet: 'omnivore', food: 'fruit', sound: 'Croak',
      size: 2, speed: 3, fierce: 2, pre: ['Tou', 'Touc'], suf: ['can', 'ucan'],
      head: 'the head of a toucan with bright blue eye rings', body: 'the glossy black body of a toucan', covering: 'glossy black feathers',
      extras: [['beak', 'an enormous rainbow-colored beak'], ['chest', 'a bright yellow bib'], ['tail', 'a long black tail']],
      powers: ['A beak that works like air-conditioning', 'Tossing fruit into its mouth'], temper: ['goofy', 'social'], names: ['Tiko', 'Rainbow', 'Papaya'] },
    { id: 'ostrich', name: 'Ostrich', emoji: '🪶', group: 'bird', habitat: 'savanna', diet: 'omnivore', food: 'seeds', sound: 'Boom',
      size: 5, speed: 5, fierce: 3, pre: ['Ost', 'Ostri'], suf: ['trich', 'rich'],
      head: 'the small head of an ostrich with huge eyes and long eyelashes', body: 'the huge, fluffy body of an ostrich', covering: 'fluffy black-and-white plumes',
      extras: [['legs', 'long, powerful bare legs'], ['neck', 'a long, bare pink neck'], ['feet', 'two-toed clawed feet']],
      powers: ['Sprinting at 70 km/h', 'Eyes bigger than its brain'], temper: ['speedy', 'goofy'], names: ['Ozzy', 'Plume', 'Olive'] },
    { id: 'chicken', name: 'Chicken', emoji: '🐔', group: 'bird', habitat: 'farm', diet: 'omnivore', food: 'corn', sound: 'Bawk',
      size: 2, speed: 2, fierce: 2, pre: ['Chick', 'Chicke'], suf: ['hen', 'icken'],
      head: 'the head of a rooster with a bright red comb and wattles', body: 'the plump, feathered body of a chicken', covering: 'russet-brown feathers',
      extras: [['tail', 'an arching tail of glossy feathers'], ['feet', 'scaly yellow chicken feet'], ['wings', 'stubby flapping wings']],
      powers: ['Being a living relative of T. rex', 'Waking everyone up at dawn'], temper: ['feisty', 'curious'], names: ['Nugget', 'Henrietta', 'Clucky'] },

    // ---------- reptiles & amphibians ----------
    { id: 'crocodile', name: 'Crocodile', emoji: '🐊', group: 'reptile', habitat: 'wetlands', diet: 'carnivore', food: 'fish', sound: 'Chomp',
      size: 5, speed: 3, fierce: 5, pre: ['Croco', 'Croc'], suf: ['odile', 'dile'],
      head: 'the long, toothy snout of a crocodile with bumpy eyes on top', body: 'the long, armoured body of a crocodile', covering: 'rough, scaly olive-green armour',
      extras: [['tail', 'a thick, powerful swimming tail'], ['back', 'rows of bony plates along its back'], ['legs', 'short, sprawling clawed legs']],
      powers: ['The strongest bite on the planet', 'Hiding underwater with just its eyes showing'], temper: ['sneaky', 'fierce'], names: ['Chomper', 'Tick-Tock', 'Snapper'] },
    { id: 'turtle', name: 'Sea Turtle', emoji: '🐢', group: 'reptile', habitat: 'ocean', diet: 'herbivore', food: 'seagrass', sound: 'Blub',
      size: 3, speed: 1, fierce: 1, pre: ['Tur', 'Turt'], suf: ['urtle', 'tle'],
      head: 'the beaked head of a sea turtle with wise, ancient eyes', body: 'the streamlined body of a sea turtle', covering: 'green-and-gold scaly skin',
      extras: [['shell', 'a big, domed, patterned shell'], ['flippers', 'long, paddle-shaped flippers'], ['tail', 'a short, stubby tail']],
      powers: ['Living for more than 80 years', 'Navigating oceans by Earth’s magnetism'], temper: ['calm', 'gentle'], names: ['Shelly', 'Myrtle', 'Sheldon'] },
    { id: 'chameleon', name: 'Chameleon', emoji: '🦎', group: 'reptile', habitat: 'rainforest', diet: 'insectivore', food: 'crickets', sound: 'Hiss',
      size: 1, speed: 1, fierce: 2, pre: ['Chame', 'Cham'], suf: ['meleon', 'eleon'],
      head: 'the helmeted head of a chameleon with swivelling cone-shaped eyes', body: 'the lumpy, leaf-shaped body of a chameleon', covering: 'bumpy scales in shifting rainbow colors',
      extras: [['tail', 'a curly gripping tail'], ['tongue', 'a super-long sticky tongue'], ['feet', 'mitten-like grasping feet']],
      powers: ['Changing color at will', 'A tongue that fires faster than a blink'], temper: ['sneaky', 'shy'], names: ['Kaleido', 'Chroma', 'Ziggy'] },
    { id: 'python', name: 'Python', emoji: '🐍', group: 'reptile', habitat: 'rainforest', diet: 'carnivore', food: 'rats', sound: 'Hiss',
      size: 4, speed: 2, fierce: 4, pre: ['Py', 'Pyth'], suf: ['thon', 'ython'],
      head: 'the wedge-shaped head of a python with a flicking forked tongue', body: 'the long, coiling body of a python', covering: 'smooth, glossy scales',
      extras: [['tail', 'a long, coiling serpent tail'], ['pattern', 'a diamond pattern of brown and gold'], ['eyes', 'hypnotic slit-pupil eyes']],
      powers: ['Swallowing meals bigger than its head', 'Sensing body heat in the dark'], temper: ['sneaky', 'calm'], names: ['Monty', 'Noodle', 'Slinky'] },
    { id: 'komodo-dragon', name: 'Komodo Dragon', emoji: '🐉', group: 'reptile', habitat: 'savanna', diet: 'carnivore', food: 'deer', sound: 'Rasp',
      size: 4, speed: 3, fierce: 5, pre: ['Komo', 'Drago'], suf: ['dragon', 'odo'],
      head: 'the broad, scaly head of a Komodo dragon with a long yellow forked tongue', body: 'the heavy, muscular body of a Komodo dragon', covering: 'rough, bumpy grey-brown scales',
      extras: [['tail', 'a long, heavy lizard tail'], ['feet', 'curved, clawed feet'], ['back', 'a leathery, armoured back']],
      powers: ['A venomous bite', 'Smelling dinner from kilometres away'], temper: ['fierce', 'sneaky'], names: ['Draco', 'Scorch', 'Rex'] },
    { id: 'frog', name: 'Tree Frog', emoji: '🐸', group: 'reptile', habitat: 'rainforest', diet: 'insectivore', food: 'flies', sound: 'Ribbit',
      size: 1, speed: 3, fierce: 1, pre: ['Fro', 'Frog'], suf: ['og', 'rog'],
      head: 'the head of a red-eyed tree frog with huge bulging red eyes', body: 'the small, bright-green body of a tree frog', covering: 'smooth, shiny green skin',
      extras: [['feet', 'sticky orange toe pads'], ['legs', 'long, springy back legs'], ['sides', 'bright blue stripes on its sides']],
      powers: ['Jumping 20 times its own length', 'Drinking water through its skin'], temper: ['playful', 'goofy'], names: ['Ribbit', 'Hopper', 'Lily'] },
    { id: 'axolotl', name: 'Axolotl', emoji: '🦎', group: 'reptile', habitat: 'wetlands', diet: 'carnivore', food: 'worms', sound: 'Blub',
      size: 1, speed: 2, fierce: 1, pre: ['Axo', 'Axol'], suf: ['lotl', 'olotl'],
      head: 'the wide, smiling head of a pink axolotl', body: 'the soft, salamander body of an axolotl', covering: 'smooth, glossy pink skin',
      extras: [['gills', 'feathery, frilly gills on each side of the head'], ['tail', 'a long finned tail'], ['feet', 'tiny four-fingered feet']],
      powers: ['Regrowing lost limbs', 'Staying baby-faced forever'], temper: ['goofy', 'gentle'], names: ['Axel', 'Bubblegum', 'Lotl'] },

    // ---------- ocean life ----------
    { id: 'shark', name: 'Shark', emoji: '🦈', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'seals', sound: 'Gulp',
      size: 5, speed: 4, fierce: 5, pre: ['Shar', 'Shark'], suf: ['ark', 'hark'],
      head: 'the pointed head of a great white shark with rows of jagged teeth', body: 'the torpedo-shaped body of a shark', covering: 'rough grey skin with a white underbelly',
      extras: [['fin', 'a tall triangular dorsal fin'], ['tail', 'a crescent-shaped tail fin'], ['gills', 'five gill slits']],
      powers: ['Sensing the electric fields of other animals', 'Growing thousands of replacement teeth'], temper: ['fierce', 'curious'], names: ['Finn', 'Chompers', 'Razor'] },
    { id: 'dolphin', name: 'Dolphin', emoji: '🐬', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'fish', sound: 'Click',
      size: 4, speed: 5, fierce: 2, pre: ['Dol', 'Dolph'], suf: ['phin', 'olphin'],
      head: 'the smiling head of a bottlenose dolphin with a short beak', body: 'the sleek, grey body of a dolphin', covering: 'smooth, rubbery grey skin',
      extras: [['fin', 'a curved dorsal fin'], ['flippers', 'smooth pectoral flippers'], ['tail', 'a powerful tail fluke']],
      powers: ['Echolocation', 'Sleeping with half its brain at a time'], temper: ['playful', 'smart'], names: ['Squeaky', 'Splash', 'Delphi'] },
    { id: 'whale', name: 'Humpback Whale', emoji: '🐋', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'krill', sound: 'Whooo',
      size: 5, speed: 2, fierce: 2, pre: ['Wha', 'Whal'], suf: ['ale', 'hale'],
      head: 'the knobbly head of a humpback whale with a long pleated throat', body: 'the enormous, blue-grey body of a humpback whale', covering: 'smooth, barnacle-dotted blue-grey skin',
      extras: [['flippers', 'extra-long, wing-like flippers'], ['tail', 'a gigantic tail fluke'], ['blowhole', 'a blowhole spraying mist']],
      powers: ['Singing songs that last for hours', 'Leaping clean out of the water'], temper: ['gentle', 'majestic'], names: ['Moby', 'Humphrey', 'Big Blue'] },
    { id: 'octopus', name: 'Octopus', emoji: '🐙', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'crabs', sound: 'Blub',
      size: 2, speed: 3, fierce: 2, pre: ['Octo', 'Oct'], suf: ['topus', 'opus'],
      head: 'the bulbous, wrinkly head of an octopus with clever golden eyes', body: 'the soft, squishy body of an octopus', covering: 'soft reddish skin',
      extras: [['tentacles', 'eight long, curling tentacles with suckers'], ['skin', 'color-changing camouflage skin'], ['ink', 'a puff of dark ink']],
      powers: ['Three hearts and blue blood', 'Squeezing through any gap bigger than its beak'], temper: ['smart', 'sneaky'], names: ['Inky', 'Octavia', 'Squiggles'] },
    { id: 'jellyfish', name: 'Jellyfish', emoji: '🪼', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'plankton', sound: 'Wobble',
      size: 2, speed: 1, fierce: 3, pre: ['Jelly', 'Jell'], suf: ['jelly', 'elly'],
      head: 'a glowing, see-through jellyfish bell for a head', body: 'the see-through, bell-shaped body of a jellyfish', covering: 'translucent, glowing jelly',
      extras: [['tentacles', 'long, trailing stinging tentacles'], ['glow', 'a soft bioluminescent glow'], ['frills', 'frilly, ribbon-like arms']],
      powers: ['Having no brain and doing just fine', 'Glowing in the dark'], temper: ['calm', 'dreamy'], names: ['Wobbles', 'Glow', 'Jelly Bean'] },
    { id: 'seahorse', name: 'Seahorse', emoji: '🌊', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'tiny shrimp', sound: 'Click',
      size: 1, speed: 1, fierce: 1, pre: ['Sea', 'Seaho'], suf: ['horse', 'orse'],
      head: 'the horse-like head of a seahorse with a long tube snout', body: 'the upright, curled body of a seahorse', covering: 'knobbly, bony orange plates',
      extras: [['tail', 'a curly gripping tail'], ['fin', 'a fluttering little back fin'], ['crest', 'a tiny crown-like crest']],
      powers: ['Dads carry the babies', 'Eyes that move independently'], temper: ['shy', 'gentle'], names: ['Seabiscuit', 'Curly', 'Pip'] },
    { id: 'crab', name: 'Crab', emoji: '🦀', group: 'ocean', habitat: 'ocean', diet: 'omnivore', food: 'algae', sound: 'Snap',
      size: 1, speed: 2, fierce: 3, pre: ['Cra', 'Crab'], suf: ['rab', 'crab'],
      head: 'the flat, armoured face of a crab with twitchy mouthparts', body: 'the wide, armoured body of a crab', covering: 'a hard, bright-red shell',
      extras: [['claws', 'two big snapping pincers'], ['legs', 'eight spiky sideways-walking legs'], ['eyes', 'eyes on stalks']],
      powers: ['Speed-walking sideways', 'Regrowing lost claws'], temper: ['grumpy', 'feisty'], names: ['Pinchy', 'Clawdia', 'Crusty'] },
    { id: 'narwhal', name: 'Narwhal', emoji: '🐳', group: 'ocean', habitat: 'polar', diet: 'carnivore', food: 'Arctic cod', sound: 'Click',
      size: 4, speed: 3, fierce: 2, pre: ['Nar', 'Narw'], suf: ['whal', 'wal'],
      head: 'the rounded, mottled head of a narwhal', body: 'the plump, speckled grey body of a narwhal', covering: 'smooth, mottled grey-and-white skin',
      extras: [['tusk', 'a long, spiraled ivory tusk growing from its head'], ['flippers', 'small rounded flippers'], ['tail', 'a curved tail fluke']],
      powers: ['A tusk with 10 million nerve endings', 'Diving 1,500 metres under the ice'], temper: ['shy', 'majestic'], names: ['Tusky', 'Nora', 'Sparkle'] },
    { id: 'pufferfish', name: 'Pufferfish', emoji: '🐡', group: 'ocean', habitat: 'ocean', diet: 'carnivore', food: 'shellfish', sound: 'Pop',
      size: 1, speed: 1, fierce: 3, pre: ['Puff', 'Puffer'], suf: ['puff', 'uffer'],
      head: 'the round, goofy face of a pufferfish with big surprised eyes', body: 'the round, puffed-up body of a pufferfish', covering: 'spotted, yellow-brown skin',
      extras: [['spikes', 'spiky puffed-up spines'], ['fins', 'tiny fluttering fins'], ['mouth', 'a pouty, beak-like mouth']],
      powers: ['Inflating into a spiky ball', 'Drawing art in the sand'], temper: ['goofy', 'shy'], names: ['Puffy', 'Popcorn', 'Balloon'] },

    // ---------- bugs ----------
    { id: 'butterfly', name: 'Butterfly', emoji: '🦋', group: 'bug', habitat: 'garden', diet: 'herbivore', food: 'nectar', sound: 'Flutter',
      size: 1, speed: 3, fierce: 1, pre: ['Butter', 'Flutter'], suf: ['fly', 'erfly'],
      head: 'the tiny head of a butterfly with big compound eyes', body: 'the slender, fuzzy body of a butterfly', covering: 'velvety black-and-orange scales',
      extras: [['wings', 'huge orange-and-black patterned butterfly wings'], ['antennae', 'long, club-tipped antennae'], ['tongue', 'a curly, straw-like tongue']],
      powers: ['Tasting with its feet', 'Migrating thousands of kilometres'], temper: ['gentle', 'dreamy'], names: ['Flutterby', 'Monarch', 'Papillon'] },
    { id: 'bee', name: 'Bumblebee', emoji: '🐝', group: 'bug', habitat: 'garden', diet: 'herbivore', food: 'pollen', sound: 'Buzz',
      size: 1, speed: 3, fierce: 2, pre: ['Bee', 'Buzz'], suf: ['bee', 'buzz'],
      head: 'the fuzzy head of a bumblebee with big compound eyes and antennae', body: 'the round, fuzzy body of a bumblebee', covering: 'fuzzy golden fur',
      extras: [['pattern', 'bold yellow-and-black stripes'], ['wings', 'small, shimmering see-through wings'], ['legs', 'pollen-dusted legs']],
      powers: ['Buzzing flowers to shake the pollen loose', 'Shivering its muscles to warm up on cold days'], temper: ['social', 'feisty'], names: ['Buzzy', 'Honey', 'Bumble'] },
    { id: 'ladybug', name: 'Ladybug', emoji: '🐞', group: 'bug', habitat: 'garden', diet: 'carnivore', food: 'aphids', sound: 'Zip',
      size: 1, speed: 2, fierce: 1, pre: ['Lady', 'Ladyb'], suf: ['bug', 'ybug'],
      head: 'the tiny black head of a ladybug with white cheek spots', body: 'the round, domed body of a ladybug', covering: 'a glossy red shell',
      extras: [['pattern', 'bold black polka dots'], ['wings', 'tiny wings tucked under its shell'], ['legs', 'six tiny black legs']],
      powers: ['Eating 5,000 aphids in a lifetime', 'Squirting stinky yellow goo at predators'], temper: ['gentle', 'playful'], names: ['Dotty', 'Scarlet', 'Lucky'] },
    { id: 'scorpion', name: 'Scorpion', emoji: '🦂', group: 'bug', habitat: 'desert', diet: 'carnivore', food: 'crickets', sound: 'Hiss',
      size: 1, speed: 2, fierce: 5, pre: ['Scorp', 'Scor'], suf: ['pion', 'orpion'],
      head: 'the armoured head of a scorpion with tiny eyes', body: 'the segmented, armoured body of a scorpion', covering: 'a shiny amber exoskeleton',
      extras: [['tail', 'a curled, segmented tail with a venomous stinger'], ['claws', 'big grabbing pincers'], ['legs', 'eight jointed legs']],
      powers: ['Glowing blue under UV light', 'Surviving a whole year without food'], temper: ['fierce', 'sneaky'], names: ['Stinger', 'Amber', 'Scorpio'] },
    { id: 'snail', name: 'Snail', emoji: '🐌', group: 'bug', habitat: 'garden', diet: 'herbivore', food: 'lettuce', sound: 'Slurp',
      size: 1, speed: 1, fierce: 1, pre: ['Snai', 'Sna'], suf: ['nail', 'ail'],
      head: 'the head of a snail with two eyes on tall wiggly stalks', body: 'the soft, slimy body of a snail', covering: 'moist, glistening grey skin',
      extras: [['shell', 'a spiral shell on its back'], ['trail', 'a shiny slime trail'], ['foot', 'one big muscular foot']],
      powers: ['Napping for up to three years', 'Carrying its house everywhere'], temper: ['calm', 'sleepy'], names: ['Speedy', 'Escargot', 'Sluggo'] }
  ];

  // Real-world hybrids and legendary creatures. Order within a pair doesn't matter.
  // `head` / `body` pin the anatomy so legends look like their myths.
  const KNOWN_HYBRIDS = [
    { a: 'lion', b: 'tiger', name: 'Liger', kind: 'real' },
    { a: 'leopard', b: 'lion', name: 'Leopon', kind: 'real' },
    { a: 'zebra', b: 'horse', name: 'Zorse', kind: 'real' },
    { a: 'zebra', b: 'donkey', name: 'Zonkey', kind: 'real' },
    { a: 'horse', b: 'donkey', name: 'Mule', kind: 'real' },
    { a: 'camel', b: 'llama', name: 'Cama', kind: 'real' },
    { a: 'goat', b: 'sheep', name: 'Geep', kind: 'real' },
    { a: 'polar-bear', b: 'grizzly-bear', name: 'Pizzly Bear', kind: 'real' },
    { a: 'whale', b: 'dolphin', name: 'Wholphin', kind: 'real' },
    { a: 'wolf', b: 'dog', name: 'Wolfdog', kind: 'real' },
    { a: 'lion', b: 'eagle', name: 'Griffin', kind: 'legendary', head: 'eagle', body: 'lion' },
    { a: 'horse', b: 'eagle', name: 'Pegasus', kind: 'legendary', head: 'horse', body: 'horse', covering: 'a gleaming pure-white coat' },
    { a: 'horse', b: 'narwhal', name: 'Unicorn', kind: 'legendary', head: 'horse', body: 'horse', covering: 'a shimmering pure-white coat' },
    { a: 'lion', b: 'scorpion', name: 'Manticore', kind: 'legendary', head: 'lion', body: 'lion' },
    { a: 'horse', b: 'seahorse', name: 'Hippocampus', kind: 'legendary', head: 'horse', body: 'seahorse' },
    { a: 'chicken', b: 'python', name: 'Cockatrice', kind: 'legendary', head: 'chicken', body: 'chicken' },
    { a: 'lion', b: 'goat', name: 'Chimera', kind: 'legendary', head: 'lion', body: 'lion' },
    { a: 'komodo-dragon', b: 'bat', name: 'Wyvern', kind: 'legendary', head: 'komodo-dragon', body: 'komodo-dragon' },
    { a: 'octopus', b: 'whale', name: 'Kraken', kind: 'legendary', head: 'octopus', body: 'whale' },
    { a: 'rabbit', b: 'moose', name: 'Jackalope', kind: 'legendary', head: 'rabbit', body: 'rabbit' }
  ];

  return {
    GROUPS,
    HABITATS,
    DIETS,
    TEMPERAMENTS,
    SIZES,
    SPEED_LABELS,
    FIERCE_LABELS,
    FIERCE_WORDS,
    ANIMALS,
    KNOWN_HYBRIDS
  };
});
