/*
 * Unique Animal Generator — breed data and name pools.
 *
 * Each breed describes what it looks like and how it behaves. The generator
 * blends two breeds' traits to write the image prompt, the breed description
 * and the pet-name suggestions.
 *
 *   pre / suf  word fragments used to build a cross-breed name (e.g. "Labra" + "doodle")
 *   size       1 (toy / petite) .. 5 (giant)
 *   energy     1 (couch potato) .. 5 (non-stop)
 *   floof      1 (sleek or hairless) .. 5 (maximum fluff)
 *   colors     keys into COLORS
 *   temper     keys into TEMPERAMENTS
 *   tags       keys into LOOK_TAGS (used for name ideas and coat blending)
 *   look       [part, phrase] pairs; the generator never uses two phrases for the same part
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.UAGData = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const COLORS = {
    black: { label: 'Black', phrase: 'glossy solid black', pool: 'black' },
    white: { label: 'White', phrase: 'pure white', pool: 'white' },
    cream: { label: 'Cream', phrase: 'soft cream', pool: 'cream' },
    golden: { label: 'Golden', phrase: 'warm golden', pool: 'golden' },
    red: { label: 'Red', phrase: 'rich red-ginger', pool: 'red' },
    chocolate: { label: 'Chocolate', phrase: 'deep chocolate brown', pool: 'chocolate' },
    grey: { label: 'Blue-grey', phrase: 'smoky blue-grey', pool: 'grey' },
    silver: { label: 'Silver', phrase: 'shimmering silver', pool: 'silver' },
    saltPepper: { label: 'Salt & pepper', phrase: 'salt-and-pepper grey', pool: 'grey' },
    apricot: { label: 'Apricot', phrase: 'apricot', pool: 'apricot' },
    fawn: { label: 'Fawn', phrase: 'light fawn', pool: 'fawn' },
    blackTan: { label: 'Black & tan', phrase: 'black with tan markings on the face, chest and legs', pool: 'blackTan' },
    blueTan: { label: 'Blue & tan', phrase: 'steel blue with golden-tan face and legs', pool: 'blueTan' },
    brindle: { label: 'Brindle', phrase: 'tiger-striped brindle', pool: 'brindle' },
    merle: { label: 'Blue merle', phrase: 'marbled blue merle', pool: 'merle' },
    tricolor: { label: 'Tricolor', phrase: 'tricolor black, white and tan', pool: 'tricolor' },
    bicolor: { label: 'Black & white', phrase: 'black and white', pool: 'bicolor' },
    greyWhite: { label: 'Grey & white', phrase: 'grey and white', pool: 'greyWhite' },
    redWhite: { label: 'Red & white', phrase: 'red and white', pool: 'redWhite' },
    tanWhite: { label: 'Tan & white', phrase: 'white with tan patches', pool: 'redWhite' },
    blenheim: { label: 'Chestnut & white', phrase: 'chestnut and white', pool: 'redWhite' },
    sable: { label: 'Sable', phrase: 'rich sable brown', pool: 'sable' },
    spotted: { label: 'Spotted', phrase: 'white with bold black spots', pool: 'spotted' },
    leopard: { label: 'Leopard-spotted', phrase: 'golden with bold black leopard spots', pool: 'spotted' },
    rosetted: { label: 'Rosetted', phrase: 'golden with dark marbled leopard-like rosettes', pool: 'spotted' },
    silverSpotted: { label: 'Silver spotted', phrase: 'silver with crisp dark spots', pool: 'spotted' },
    pointed: { label: 'Colorpoint', phrase: 'pale cream with dark seal-brown points on the face, ears, paws and tail', pool: 'pointed' },
    mitted: { label: 'Mitted colorpoint', phrase: 'pale colorpoint with a white chest and white mitten paws', pool: 'pointed' },
    tabby: { label: 'Tabby', phrase: 'brown tabby-striped', pool: 'tabby' },
    ticked: { label: 'Ticked', phrase: 'warm ruddy ticked', pool: 'ticked' },
    tortie: { label: 'Tortoiseshell', phrase: 'mottled black-and-orange tortoiseshell', pool: 'tortie' },
    calico: { label: 'Calico', phrase: 'calico white, orange and black patched', pool: 'calico' },
    van: { label: 'Van-patterned', phrase: 'white with auburn patches on the head and a ringed auburn tail', pool: 'redWhite' }
  };

  const TEMPERAMENTS = {
    energetic: { adj: 'energetic', names: ['Rocket', 'Zoom', 'Dash', 'Turbo', 'Bolt', 'Sparky'] },
    gentle: { adj: 'gentle', names: ['Angel', 'Teddy', 'Dove', 'Mellow', 'Sunny', 'Bambi'] },
    smart: { adj: 'clever', names: ['Einstein', 'Sherlock', 'Newton', 'Ada', 'Darwin', 'Watson'] },
    playful: { adj: 'playful', names: ['Scamp', 'Bingo', 'Pickles', 'Gizmo', 'Rascal', 'Zippy'] },
    regal: { adj: 'dignified', names: ['Duchess', 'Sir Reginald', 'Baron', 'Countess', 'Lord Fluffington', 'Majesty'] },
    loyal: { adj: 'loyal', names: ['Hero', 'Ace', 'Captain', 'Ranger', 'Valor', 'Sergeant'] },
    brave: { adj: 'brave', names: ['Blaze', 'Bruiser', 'Maverick', 'Rebel', 'Diesel'] },
    cuddly: { adj: 'affectionate', names: ['Snuggles', 'Cuddles', 'Sweetpea', 'Lovebug', 'Buttercup', 'Huggy'] },
    independent: { adj: 'independent', names: ['Indie', 'Nomad', 'Solo', 'Rogue', 'Maverick'] },
    chatty: { adj: 'chatty', names: ['Chatterbox', 'Aria', 'Echo', 'Opera', 'Jazz'] },
    calm: { adj: 'laid-back', names: ['Zen', 'Snooze', 'Dozer', 'Mellow', 'Loaf', 'Sunday'] },
    mischievous: { adj: 'mischievous', names: ['Loki', 'Gremlin', 'Bandit', 'Mischief', 'Trouble'] },
    wild: { adj: 'adventurous', names: ['Safari', 'Jungle', 'Rumble', 'Wild Thing', 'Tarzan'] },
    curious: { adj: 'curious', names: ['Scout', 'Columbus', 'Nosey', 'Explorer', 'Sherlock'] }
  };

  const LOOK_TAGS = {
    curly: { why: 'For those irresistible curls', names: ['Noodle', 'Doodle', 'Curly', 'Ramen', 'Ringo', 'Frizzle'] },
    fluffy: { why: 'Because that floof is next level', names: ['Floof', 'Cloud', 'Cotton', 'Fluffernutter', 'Puffin', 'Dandelion'] },
    silky: { why: 'For that silky, flowing coat', names: ['Silky', 'Satin', 'Ribbon', 'Chiffon', 'Velvet'] },
    plush: { why: 'For that teddy-bear plush coat', names: ['Teddy', 'Plushie', 'Winnie', 'Pudding', 'Bear'] },
    sleek: { why: 'Suits a sleek, shiny coat', names: ['Velvet', 'Satin', 'Silk', 'Suede', 'Slick'] },
    wiry: { why: 'For a charmingly scruffy look', names: ['Scruffy', 'Bristle', 'Rufus', 'Tumbleweed', 'Moppet'] },
    hairless: { why: 'Made for that velvety, fuzz-free look', names: ['Peach Fuzz', 'Raisin', 'Suede', 'Pinky', 'Velvet'] },
    wrinkly: { why: 'For all those adorable wrinkles', names: ['Wrinkles', 'Pugsley', 'Raisin', 'Crinkle', 'Winston'] },
    spotted: { why: 'Inspired by those striking spots', names: ['Domino', 'Freckles', 'Dotty', 'Pixel', 'Speckles'] },
    foldEars: { why: 'For those owl-like folded ears', names: ['Origami', 'Hoot', 'Owlet', 'Pretzel', 'Tuck'] },
    bobtail: { why: 'For that cute stubby tail', names: ['Stumpy', 'Nub', 'Pom Pom', 'Bunny', 'Bobbin'] },
    shortLegs: { why: 'Short legs, big personality', names: ['Scooter', 'Shorty', 'Sausage', 'Loaf', 'Stubbs', 'Waddles'] },
    bigEars: { why: 'For those satellite-dish ears', names: ['Radar', 'Bat', 'Satellite', 'Antenna', 'Jackrabbit'] },
    tufted: { why: 'For those wild, lynx-tipped ears', names: ['Lynx', 'Timber', 'Bramble', 'Aspen', 'Pine'] },
    speedy: { why: 'Built for speed', names: ['Flash', 'Arrow', 'Comet', 'Blitz', 'Zippy'] },
    mane: { why: 'Fit for a lion-like mane', names: ['Leo', 'Lionel', 'Mane Event', 'Rory', 'Kingston'] },
    wolfish: { why: 'For that wild, wolfish look', names: ['Wolfie', 'Ghost', 'Timber', 'Luna', 'Kodiak'] }
  };

  const COLOR_NAMES = {
    black: ['Shadow', 'Onyx', 'Midnight', 'Raven', 'Licorice', 'Pepper', 'Ninja', 'Jet'],
    white: ['Snowball', 'Casper', 'Marshmallow', 'Frost', 'Pearl', 'Blizzard', 'Coconut', 'Yeti'],
    cream: ['Custard', 'Vanilla', 'Butter', 'Latte', 'Oatmeal', 'Buttercream'],
    golden: ['Honey', 'Sunny', 'Goldie', 'Butterscotch', 'Marigold', 'Nugget'],
    red: ['Rusty', 'Ginger', 'Cinnamon', 'Paprika', 'Pumpkin', 'Maple'],
    chocolate: ['Cocoa', 'Mocha', 'Fudge', 'Brownie', 'Truffle', 'Espresso'],
    grey: ['Smokey', 'Storm', 'Ash', 'Slate', 'Misty', 'Pewter'],
    silver: ['Sterling', 'Silver', 'Nickel', 'Comet', 'Moonbeam'],
    apricot: ['Apricot', 'Peaches', 'Mango', 'Sorbet', 'Clementine'],
    fawn: ['Toffee', 'Caramel', 'Peanut', 'Almond', 'Pretzel'],
    blackTan: ['Bandit', 'Smudge', 'Rocco', 'Hickory', 'Tootsie'],
    blueTan: ['Blue', 'Denim', 'Indigo', 'Bluebell'],
    brindle: ['Tiger', 'Chai', 'Marble', 'Stripes', 'Tigerlily'],
    merle: ['Marble', 'Galaxy', 'Opal', 'Nebula', 'Cosmo'],
    tricolor: ['Patch', 'Neapolitan', 'Trixie', 'Mosaic', 'Harlequin'],
    bicolor: ['Tux', 'Domino', 'Panda', 'Magpie', 'Piano'],
    greyWhite: ['Storm', 'Nimbus', 'Wolfie', 'Frosty', 'Cloud'],
    redWhite: ['Foxy', 'Rusty', 'Saffron', 'Clementine', 'Autumn'],
    sable: ['Sable', 'Mink', 'Espresso', 'Hazel', 'Chestnut'],
    spotted: ['Domino', 'Freckles', 'Dotty', 'Pixel', 'Speckles', 'Polka'],
    pointed: ['Latte', 'Smudge', 'Socks', 'Mocha', 'Toasty'],
    tabby: ['Tigger', 'Stripes', 'Ziggy', 'Mackerel', 'Tiger'],
    ticked: ['Amber', 'Sahara', 'Nutmeg', 'Sandy', 'Cinnamon'],
    tortie: ['Tortie', 'Mosaic', 'Autumn', 'Pebbles', 'Maple'],
    calico: ['Patches', 'Confetti', 'Calliope', 'Quilt', 'Callie']
  };

  const ORIGIN_NAMES = {
    England: ['Winston', 'Pippa', 'Crumpet', 'Bramble', 'Earl Grey', 'Beatrix', 'Wellington'],
    Scotland: ['Angus', 'Hamish', 'Isla', 'Murray', 'Heather', 'Bonnie', 'Nessie'],
    Ireland: ['Finn', 'Murphy', 'Clover', 'Seamus', 'Maeve', 'Shamrock'],
    Wales: ['Dylan', 'Bryn', 'Cerys', 'Rhys', 'Gwen'],
    France: ['Pierre', 'Colette', 'Bijou', 'Gigi', 'Brioche', 'Croissant'],
    Germany: ['Fritz', 'Greta', 'Otto', 'Heidi', 'Pretzel', 'Klaus', 'Liesl'],
    Switzerland: ['Heidi', 'Fondue', 'Matterhorn', 'Alpine', 'Edelweiss'],
    Russia: ['Misha', 'Sasha', 'Nikolai', 'Anya', 'Boris', 'Blini', 'Tundra'],
    Norway: ['Freya', 'Thor', 'Loki', 'Fjord', 'Sven', 'Astrid'],
    China: ['Bao', 'Mei', 'Dumpling', 'Lychee', 'Wonton'],
    Japan: ['Yuki', 'Hana', 'Mochi', 'Sora', 'Kenji', 'Kiko'],
    Tibet: ['Tashi', 'Lhasa', 'Everest', 'Yeti', 'Pema'],
    Mexico: ['Churro', 'Coco', 'Frida', 'Diego', 'Pepita'],
    USA: ['Scout', 'Buddy', 'Liberty', 'Hank', 'Daisy', 'Dakota'],
    'Maine, USA': ['Moose', 'Acadia', 'Blueberry', 'Skipper', 'Bangor'],
    Alaska: ['Kodiak', 'Nanook', 'Juneau', 'Denali', 'Aurora'],
    Canada: ['Maple', 'Moose', 'Poutine', 'Timber', 'Mountie'],
    Croatia: ['Luka', 'Zara', 'Adria', 'Mila', 'Dubrovnik'],
    Malta: ['Melita', 'Valletta', 'Coral', 'Gozo'],
    Cuba: ['Havana', 'Rumba', 'Mambo', 'Salsa', 'Cha-Cha'],
    Hungary: ['Paprika', 'Bela', 'Goulash', 'Zsa Zsa', 'Buda'],
    Thailand: ['Mali', 'Pim', 'Siam', 'Lemongrass', 'Noi'],
    Myanmar: ['Mandalay', 'Ruby', 'Jade', 'Saffron'],
    Iran: ['Darius', 'Cyrus', 'Soraya', 'Saffron', 'Pistachio', 'Shiraz'],
    Turkey: ['Pasha', 'Sultan', 'Lokum', 'Mavi', 'Simit'],
    Egypt: ['Cleo', 'Ramses', 'Nefertiti', 'Pharaoh', 'Tut'],
    Ethiopia: ['Sheba', 'Kaffa', 'Axum', 'Mocha'],
    'Isle of Man': ['Laxey', 'Douglas', 'Ellan', 'Snaefell']
  };

  const SIZE_NAMES = {
    dog: [
      ['Peanut', 'Pip', 'Bean', 'Nugget', 'Button', 'Pixie', 'Jellybean'],
      ['Biscuit', 'Pickles', 'Muffin', 'Waffles', 'Poppy', 'Sprout'],
      ['Milo', 'Rosie', 'Charlie', 'Ollie', 'Ruby', 'Buddy'],
      ['Bear', 'Duke', 'Bruno', 'Rocky', 'Juno', 'Atlas'],
      ['Moose', 'Titan', 'Hercules', 'Goliath', 'Tank', 'Bigfoot']
    ],
    cat: [
      ['Pip', 'Bean', 'Mouse', 'Button', 'Pixie', 'Tinkerbell'],
      ['Mochi', 'Biscuit', 'Poppy', 'Muffin', 'Sprout'],
      ['Milo', 'Luna', 'Oliver', 'Nala', 'Ziggy', 'Olive'],
      ['Leo', 'Bear', 'Tank', 'Bigsby', 'Rocky', 'Atlas'],
      ['Lion', 'Titan', 'Chonk', 'Goliath', 'Hercules', 'Moose']
    ]
  };

  const SPECIES = {
    dog: {
      label: 'Dog',
      noun: 'dog',
      baby: 'pup',
      sizeLabels: ['Toy', 'Small', 'Medium', 'Large', 'Giant'],
      sizeWords: ['toy-sized', 'small', 'medium-sized', 'large', 'giant'],
      sizePhrases: ['tiny toy-sized', 'small', 'medium-sized', 'large', 'giant, massive'],
      sizeWhy: ['A tiny name for a toy-sized pup', 'A sweet name for a small pup', 'A classic name for a medium-sized pup', 'A big name for a big dog', 'A mighty name for a giant dog'],
      energyLabels: ['Couch potato', 'Laid-back', 'Playful', 'High-energy', 'Unstoppable'],
      energyWords: ['couch-loving', 'easygoing', 'playful', 'high-energy', 'boundless'],
      scenes: [
        'sitting on green grass in a sunny park',
        'lying on a cozy rug in a bright living room',
        'standing on a sandy beach at golden hour',
        'sitting on a wooden porch',
        'walking along an autumn forest trail',
        'sitting in a meadow of wildflowers'
      ],
      loading: ['Mixing the DNA…', 'Fluffing the fur…', 'Teaching it to sit…', 'Wagging the tail…', 'Adding extra wiggle…', 'Polishing the nose…', 'Fetching the camera…']
    },
    cat: {
      label: 'Cat',
      noun: 'cat',
      baby: 'kitty',
      sizeLabels: ['Petite', 'Small', 'Medium', 'Large', 'Extra-large'],
      sizeWords: ['petite', 'small', 'medium-sized', 'large', 'extra-large'],
      sizePhrases: ['petite', 'small', 'medium-sized', 'large', 'very large'],
      sizeWhy: ['A tiny name for a petite kitty', 'A sweet name for a small kitty', 'A classic name for a medium-sized cat', 'A big name for a big cat', 'A mighty name for a giant cat'],
      energyLabels: ['Pro napper', 'Mellow', 'Playful', 'Lively', 'Zoomies 24/7'],
      energyWords: ['sleepy', 'mellow', 'playful', 'lively', 'turbo-charged'],
      scenes: [
        'sitting on a sunny windowsill',
        'curled up on a soft blanket on a sofa',
        'sitting in a garden among flowers',
        'perched on a cozy cat tree',
        'lounging on a wooden floor in warm sunlight',
        'sitting on a bookshelf'
      ],
      loading: ['Mixing the DNA…', 'Brushing the whiskers…', 'Perfecting the side-eye…', 'Counting the toe beans…', 'Warming up the purr…', 'Knocking things off tables…', 'Finding the sunny spot…']
    }
  };

  const FLOOF_LABELS = ['Sleek', 'Short', 'Medium', 'Fluffy', 'Maximum floof'];

  // Shorthand so the breed table below stays readable.
  function breed(id, name, origin, size, energy, floof, pre, suf, colors, temper, tags, look) {
    return { id, name, origin, size, energy, floof, pre, suf, colors, temper, tags, look };
  }

  const DOGS = [
    breed('labrador-retriever', 'Labrador Retriever', 'Canada', 4, 4, 2, ['Labra', 'Lab'], ['ador', 'dor'],
      ['golden', 'black', 'chocolate'], ['cuddly', 'playful', 'loyal'], ['sleek'],
      [['head', 'a broad, friendly head'], ['tail', 'a thick otter-like tail'], ['ears', 'soft drop ears'], ['eyes', 'kind brown eyes'], ['body', 'a sturdy, athletic build']]),
    breed('golden-retriever', 'Golden Retriever', 'Scotland', 4, 4, 4, ['Golden', 'Gold'], ['golden', 'olden'],
      ['golden', 'cream', 'red'], ['gentle', 'cuddly', 'smart'], ['fluffy'],
      [['feathering', 'feathered fur on the chest and legs'], ['head', 'a broad head with a gentle expression'], ['tail', 'a plumed, feathery tail'], ['ears', 'soft feathered drop ears'], ['eyes', 'warm dark eyes']]),
    breed('german-shepherd', 'German Shepherd', 'Germany', 4, 5, 3, ['Shep', 'Shepa', 'German'], ['shepherd', 'herd'],
      ['blackTan', 'sable', 'black'], ['loyal', 'smart', 'brave'], ['bigEars'],
      [['ears', 'large erect pointed ears'], ['muzzle', 'a long, strong muzzle'], ['body', 'a noble, muscular build with a sloping back'], ['tail', 'a bushy low-hanging tail'], ['markings', 'a dark saddle marking on the back']]),
    breed('french-bulldog', 'French Bulldog', 'France', 2, 2, 1, ['Frenchie', 'French'], ['frenchie', 'bulldog'],
      ['fawn', 'brindle', 'cream', 'bicolor'], ['playful', 'cuddly', 'mischievous'], ['bigEars', 'sleek'],
      [['ears', 'big upright bat ears'], ['muzzle', 'a short, flat pushed-in muzzle'], ['body', 'a compact, muscular little body'], ['head', 'a square head with soft wrinkles'], ['eyes', 'round, wide-set eyes']]),
    breed('bulldog', 'English Bulldog', 'England', 3, 1, 1, ['Bull', 'Bulla'], ['bull', 'dog'],
      ['fawn', 'brindle', 'white', 'redWhite'], ['calm', 'cuddly', 'brave'], ['wrinkly'],
      [['head', 'a massive, wrinkly head'], ['muzzle', 'a pushed-in face with an underbite'], ['body', 'a stocky, low-slung body with a wide chest'], ['ears', 'small rose-shaped ears'], ['jowls', 'loose, droopy jowls']]),
    breed('poodle', 'Poodle', 'France', 3, 4, 4, ['Poo', 'Poodle'], ['doodle', 'poo'],
      ['white', 'black', 'apricot', 'cream', 'chocolate', 'silver'], ['smart', 'playful', 'regal'], ['curly'],
      [['muzzle', 'a long, elegant muzzle'], ['ears', 'long ears covered in curls'], ['body', 'a lean, graceful build'], ['topknot', 'a fluffy curly topknot'], ['legs', 'long, elegant legs']]),
    breed('beagle', 'Beagle', 'England', 2, 4, 2, ['Bea', 'Beag'], ['eagle', 'gle'],
      ['tricolor', 'redWhite', 'tanWhite'], ['playful', 'curious', 'cuddly'], ['sleek'],
      [['ears', 'long, velvety floppy ears'], ['eyes', 'big pleading brown eyes'], ['tail', 'a white-tipped tail held high'], ['muzzle', 'a square, medium-length muzzle'], ['body', 'a compact, sturdy body']]),
    breed('rottweiler', 'Rottweiler', 'Germany', 4, 3, 1, ['Rott', 'Rotti'], ['weiler', 'weil'],
      ['blackTan'], ['loyal', 'brave', 'calm'], ['sleek'],
      [['head', 'a broad, powerful head'], ['body', 'a massive, muscular chest'], ['markings', 'rust-colored eyebrow and cheek markings'], ['ears', 'triangular drop ears'], ['muzzle', 'a strong, square muzzle']]),
    breed('dachshund', 'Dachshund', 'Germany', 2, 3, 2, ['Dachs', 'Doxie'], ['weenie', 'shund', 'doxie'],
      ['red', 'blackTan', 'chocolate', 'merle'], ['curious', 'brave', 'mischievous'], ['shortLegs'],
      [['body', 'a long, low sausage-shaped body'], ['legs', 'short stubby legs'], ['ears', 'long rounded floppy ears'], ['muzzle', 'a long, pointed muzzle'], ['chest', 'a deep, keel-shaped chest']]),
    breed('pembroke-welsh-corgi', 'Pembroke Welsh Corgi', 'Wales', 2, 4, 3, ['Corgi', 'Cor'], ['corgi', 'orgi'],
      ['redWhite', 'sable', 'tricolor'], ['playful', 'smart', 'loyal'], ['shortLegs', 'bigEars'],
      [['legs', 'short stubby legs'], ['ears', 'large upright fox-like ears'], ['body', 'a long, low body with a fluffy rear'], ['muzzle', 'a fox-like face'], ['chest', 'a fluffy white chest']]),
    breed('siberian-husky', 'Siberian Husky', 'Russia', 3, 5, 4, ['Husk', 'Husky'], ['sky', 'husky'],
      ['greyWhite', 'bicolor', 'redWhite', 'white'], ['energetic', 'mischievous', 'independent'], ['wolfish', 'fluffy'],
      [['eyes', 'striking ice-blue eyes'], ['ears', 'erect triangular ears'], ['mask', 'a wolf-like facial mask'], ['tail', 'a bushy sickle-shaped tail'], ['body', 'a lithe, athletic sled-dog build']]),
    breed('australian-shepherd', 'Australian Shepherd', 'USA', 3, 5, 3, ['Aussie', 'Auss'], ['aussie', 'ussie'],
      ['merle', 'tricolor', 'bicolor', 'redWhite'], ['energetic', 'smart', 'loyal'], ['fluffy'],
      [['eyes', 'eye-catching blue or odd-colored eyes'], ['ruff', 'a fluffy mane-like ruff'], ['ears', 'semi-folded triangular ears'], ['body', 'an agile, medium build'], ['tail', 'a short bobbed tail']]),
    breed('yorkshire-terrier', 'Yorkshire Terrier', 'England', 1, 4, 4, ['Yorki', 'York'], ['yorkie', 'orkie'],
      ['blueTan'], ['brave', 'mischievous', 'cuddly'], ['silky'],
      [['ears', 'small V-shaped erect ears'], ['topknot', 'a tiny topknot'], ['body', 'a tiny, compact body'], ['eyes', 'bright, sparkling dark eyes'], ['muzzle', 'a small, fine muzzle']]),
    breed('boxer', 'Boxer', 'Germany', 4, 5, 1, ['Box', 'Boxa'], ['boxer', 'xer'],
      ['fawn', 'brindle', 'white'], ['playful', 'energetic', 'loyal'], ['sleek'],
      [['muzzle', 'a short, square muzzle with an underbite'], ['head', 'a chiseled head with a wrinkled forehead'], ['body', 'a lean, muscular build'], ['markings', 'a white chest blaze'], ['eyes', 'dark, expressive eyes']]),
    breed('cavalier-king-charles-spaniel', 'Cavalier King Charles Spaniel', 'England', 2, 3, 4, ['Cava', 'Cav'], ['valier', 'lier'],
      ['blenheim', 'tricolor', 'red', 'blackTan'], ['cuddly', 'gentle', 'playful'], ['silky'],
      [['ears', 'long, feathered, silky ears'], ['eyes', 'large, round, dark eyes'], ['muzzle', 'a sweet, short muzzle'], ['body', 'a small, elegant body'], ['tail', 'a feathered tail']]),
    breed('shih-tzu', 'Shih Tzu', 'Tibet', 1, 2, 5, ['Shih', 'Shi'], ['tzu', 'zu'],
      ['golden', 'bicolor', 'white', 'greyWhite'], ['cuddly', 'playful', 'regal'], ['silky'],
      [['muzzle', 'a short, flat muzzle'], ['topknot', 'a topknot of hair'], ['eyes', 'large, round dark eyes'], ['beard', 'a sweeping beard and mustache'], ['body', 'a small, sturdy body']]),
    breed('pomeranian', 'Pomeranian', 'Germany', 1, 4, 5, ['Pom', 'Pomer'], ['eranian', 'ranian', 'pom'],
      ['red', 'apricot', 'cream', 'black', 'white'], ['playful', 'brave', 'curious'], ['fluffy', 'mane'],
      [['ruff', 'a huge lion-like ruff of fur'], ['muzzle', 'a tiny fox-like face'], ['ears', 'small erect ears'], ['tail', 'a plumed tail curled over the back'], ['body', 'a tiny, puffball body']]),
    breed('chihuahua', 'Chihuahua', 'Mexico', 1, 3, 1, ['Chi', 'Chihua'], ['huahua', 'hua'],
      ['fawn', 'cream', 'black', 'chocolate', 'blackTan'], ['brave', 'mischievous', 'loyal'], ['bigEars'],
      [['head', 'an apple-shaped head'], ['ears', 'enormous upright ears'], ['eyes', 'big, round, expressive eyes'], ['body', 'a tiny, delicate body'], ['legs', 'thin, dainty legs']]),
    breed('pug', 'Pug', 'China', 2, 2, 1, ['Pug', 'Puga'], ['pug'],
      ['fawn', 'black'], ['cuddly', 'playful', 'mischievous'], ['wrinkly'],
      [['muzzle', 'a flat, wrinkly face'], ['eyes', 'big round bulging eyes'], ['tail', 'a tightly curled tail'], ['body', 'a compact, square body'], ['ears', 'small, soft folded ears']]),
    breed('border-collie', 'Border Collie', 'Scotland', 3, 5, 3, ['Bor', 'Border'], ['collie', 'ollie'],
      ['bicolor', 'merle', 'redWhite', 'tricolor'], ['smart', 'energetic', 'loyal'], ['fluffy'],
      [['eyes', 'an intense, intelligent stare'], ['ears', 'semi-erect tipped ears'], ['markings', 'a white blaze and collar'], ['body', 'a lean, agile athletic build'], ['tail', 'a low, feathery tail']]),
    breed('great-dane', 'Great Dane', 'Germany', 5, 3, 1, ['Dane', 'Great'], ['dane', 'ane'],
      ['fawn', 'brindle', 'black', 'spotted', 'grey'], ['gentle', 'calm', 'loyal'], ['sleek'],
      [['body', 'a towering, giant frame'], ['head', 'a long, rectangular noble head'], ['legs', 'long, powerful legs'], ['ears', 'soft floppy ears'], ['jowls', 'loose lips and jowls']]),
    breed('doberman-pinscher', 'Doberman Pinscher', 'Germany', 4, 5, 1, ['Dober', 'Dobe'], ['berman', 'erman', 'man'],
      ['blackTan', 'chocolate'], ['loyal', 'brave', 'smart'], ['sleek'],
      [['body', 'a sleek, muscular, athletic body'], ['muzzle', 'a long, wedge-shaped muzzle'], ['markings', 'rust-colored markings above the eyes and on the muzzle'], ['ears', 'alert, high-set ears'], ['neck', 'a long, elegant neck']]),
    breed('bernese-mountain-dog', 'Bernese Mountain Dog', 'Switzerland', 5, 3, 4, ['Berne', 'Bern'], ['nese', 'ernese'],
      ['tricolor'], ['gentle', 'calm', 'cuddly'], ['fluffy'],
      [['markings', 'classic black, white and rust tricolor markings'], ['body', 'a large, sturdy build'], ['head', 'a broad, gentle head'], ['ears', 'triangular drop ears'], ['tail', 'a bushy tail']]),
    breed('shiba-inu', 'Shiba Inu', 'Japan', 2, 3, 3, ['Shiba', 'Shib'], ['inu', 'iba'],
      ['red', 'blackTan', 'cream'], ['independent', 'mischievous', 'loyal'], ['fluffy'],
      [['muzzle', 'a fox-like face with a white muzzle'], ['tail', 'a thick, curled-up tail'], ['ears', 'small, triangular erect ears'], ['eyes', 'small, deep-set triangular eyes'], ['body', 'a compact, muscular body']]),
    breed('boston-terrier', 'Boston Terrier', 'USA', 2, 4, 1, ['Bos', 'Boston'], ['ton', 'ston'],
      ['bicolor', 'brindle'], ['playful', 'cuddly', 'mischievous'], ['bigEars'],
      [['markings', 'a tuxedo-like white chest and blaze'], ['ears', 'large, erect bat ears'], ['muzzle', 'a short, square muzzle'], ['eyes', 'large, round, wide-set eyes'], ['body', 'a compact, muscular little body']]),
    breed('miniature-schnauzer', 'Miniature Schnauzer', 'Germany', 2, 4, 3, ['Schnau', 'Schnoo'], ['schnauzer', 'nauzer'],
      ['saltPepper', 'black', 'silver'], ['smart', 'playful', 'brave'], ['wiry'],
      [['beard', 'a bushy beard and mustache'], ['eyebrows', 'long, bushy eyebrows'], ['ears', 'folded V-shaped ears'], ['body', 'a square, sturdy frame'], ['legs', 'straight, furnished legs']]),
    breed('cocker-spaniel', 'Cocker Spaniel', 'England', 2, 3, 4, ['Cocka', 'Cocker'], ['cocker', 'ocker'],
      ['golden', 'black', 'chocolate', 'red'], ['cuddly', 'gentle', 'playful'], ['silky'],
      [['ears', 'long, lobular ears with silky waves'], ['eyes', 'large, soulful eyes'], ['feathering', 'silky feathering on the legs and belly'], ['head', 'a rounded head'], ['body', 'a compact, sturdy body']]),
    breed('maltese', 'Maltese', 'Malta', 1, 3, 5, ['Malti', 'Mal'], ['tese', 'ese'],
      ['white'], ['cuddly', 'playful', 'gentle'], ['silky'],
      [['eyes', 'big black button eyes'], ['nose', 'a tiny black button nose'], ['ears', 'long, hair-draped ears'], ['body', 'a tiny, dainty body'], ['tail', 'a plumed tail over the back']]),
    breed('dalmatian', 'Dalmatian', 'Croatia', 4, 5, 1, ['Dalma', 'Dal'], ['matian', 'tian'],
      ['spotted'], ['energetic', 'playful', 'loyal'], ['spotted', 'sleek'],
      [['body', 'a lean, athletic, muscular body'], ['ears', 'soft, high-set drop ears'], ['muzzle', 'a long, strong muzzle'], ['tail', 'a long, tapering tail'], ['eyes', 'bright, alert eyes']]),
    breed('bichon-frise', 'Bichon Frise', 'France', 2, 3, 5, ['Bichon', 'Bicho'], ['chon', 'ichon'],
      ['white', 'cream'], ['playful', 'cuddly', 'gentle'], ['curly', 'fluffy'],
      [['head', 'a rounded, cotton-ball head'], ['eyes', 'dark, round eyes'], ['tail', 'a plumed tail curved over the back'], ['body', 'a small, sturdy body'], ['nose', 'a black button nose']]),
    breed('jack-russell-terrier', 'Jack Russell Terrier', 'England', 2, 5, 2, ['Jack', 'Jacka'], ['russell', 'jack'],
      ['tanWhite', 'tricolor', 'bicolor'], ['energetic', 'brave', 'mischievous'], ['wiry'],
      [['body', 'a compact, athletic little body'], ['ears', 'small V-shaped folded ears'], ['markings', 'a mostly white coat with patches on the face'], ['eyes', 'almond-shaped dark eyes'], ['legs', 'springy, muscular legs']]),
    breed('saint-bernard', 'Saint Bernard', 'Switzerland', 5, 2, 4, ['Berna', 'Saint'], ['bernard', 'nard'],
      ['redWhite'], ['gentle', 'calm', 'cuddly'], ['fluffy'],
      [['head', 'a massive head with a wrinkled brow'], ['jowls', 'droopy jowls'], ['markings', 'a white blaze and chest with a dark facial mask'], ['body', 'a huge, powerful body'], ['eyes', 'soft, droopy eyes']]),
    breed('samoyed', 'Samoyed', 'Russia', 4, 4, 5, ['Samo', 'Sammy'], ['moyed', 'oyed'],
      ['white', 'cream'], ['gentle', 'playful', 'cuddly'], ['fluffy'],
      [['mouth', "the famous upturned 'Sammy smile'"], ['ears', 'erect, triangular ears'], ['tail', 'a plumed tail curled over the back'], ['body', 'a powerful, medium-large build'], ['ruff', 'a thick snowy ruff']]),
    breed('akita', 'Akita', 'Japan', 5, 3, 3, ['Aki', 'Akita'], ['kita', 'ita'],
      ['red', 'white', 'brindle'], ['loyal', 'brave', 'independent'], ['fluffy'],
      [['head', 'a large, bear-like head'], ['tail', 'a big, curled tail over the back'], ['ears', 'small, erect triangular ears'], ['eyes', 'small, deep-set dark eyes'], ['body', 'a massive, powerful build']]),
    breed('basset-hound', 'Basset Hound', 'France', 3, 1, 2, ['Bassa', 'Basset'], ['basset', 'hound'],
      ['tricolor', 'redWhite'], ['calm', 'gentle', 'loyal'], ['shortLegs'],
      [['ears', 'extremely long, droopy velvet ears'], ['eyes', 'sad, droopy eyes'], ['jowls', 'loose skin and droopy jowls'], ['legs', 'short, crooked legs'], ['body', 'a long, heavy, low body']]),
    breed('greyhound', 'Greyhound', 'England', 4, 3, 1, ['Grey', 'Greya'], ['hound', 'ound'],
      ['grey', 'black', 'brindle', 'fawn', 'white'], ['gentle', 'calm'], ['speedy', 'sleek'],
      [['body', 'a slim, aerodynamic body with a deep chest'], ['head', 'a long, narrow head'], ['legs', 'long, slender racing legs'], ['waist', 'a tucked-up waist'], ['ears', 'small rose-shaped ears']]),
    breed('whippet', 'Whippet', 'England', 2, 4, 1, ['Whip', 'Whippa'], ['whippet', 'ippet'],
      ['fawn', 'brindle', 'white', 'grey'], ['gentle', 'energetic', 'cuddly'], ['speedy', 'sleek'],
      [['body', "a slender, lightweight sprinter's body"], ['head', 'a long, narrow head'], ['legs', 'long, thin legs'], ['eyes', 'large, gentle eyes'], ['ears', 'small, folded rose ears']]),
    breed('weimaraner', 'Weimaraner', 'Germany', 4, 5, 1, ['Weima', 'Weim'], ['maraner', 'raner'],
      ['silver'], ['energetic', 'loyal', 'smart'], ['sleek'],
      [['eyes', 'striking light amber eyes'], ['ears', 'long, soft floppy ears'], ['body', 'a sleek, athletic body'], ['muzzle', 'a long, aristocratic muzzle'], ['legs', 'long, muscular legs']]),
    breed('old-english-sheepdog', 'Old English Sheepdog', 'England', 4, 3, 5, ['Sheepa', 'Sheep'], ['sheepdog', 'sheep'],
      ['greyWhite'], ['gentle', 'playful', 'cuddly'], ['fluffy'],
      [['fringe', 'shaggy hair covering the eyes'], ['body', 'a big, bear-like body'], ['head', 'a square, bearded face'], ['rear', 'a rounded, fluffy rump'], ['legs', 'thickly furred legs']]),
    breed('newfoundland', 'Newfoundland', 'Canada', 5, 2, 4, ['Newfie', 'Newf'], ['foundland', 'newfie', 'land'],
      ['black', 'chocolate', 'bicolor'], ['gentle', 'calm', 'cuddly'], ['fluffy'],
      [['head', 'a massive, broad head'], ['body', 'a huge, bear-like body'], ['eyes', 'soft, gentle eyes'], ['paws', 'big webbed paws'], ['ears', 'small, triangular drop ears']]),
    breed('alaskan-malamute', 'Alaskan Malamute', 'Alaska', 5, 4, 4, ['Mala', 'Malamu'], ['mute', 'amute', 'lamute'],
      ['greyWhite', 'bicolor', 'redWhite', 'white'], ['loyal', 'independent', 'playful'], ['wolfish', 'fluffy'],
      [['mask', 'a cap-and-mask facial marking'], ['body', 'a heavy-boned, powerful build'], ['tail', 'a plumed tail over the back'], ['ears', 'wedge-shaped erect ears'], ['eyes', 'almond-shaped brown eyes']]),
    breed('bull-terrier', 'Bull Terrier', 'England', 3, 4, 1, ['Bully'], ['bully'],
      ['white', 'brindle', 'redWhite', 'tricolor'], ['playful', 'mischievous', 'brave'], ['sleek'],
      [['head', 'an egg-shaped head with a Roman nose'], ['eyes', 'small, triangular dark eyes'], ['body', 'a muscular, barrel-chested body'], ['ears', 'small, erect ears'], ['tail', 'a short, tapering tail']]),
    breed('havanese', 'Havanese', 'Cuba', 1, 3, 5, ['Hava', 'Havan'], ['nese', 'vanese'],
      ['cream', 'white', 'chocolate', 'golden', 'bicolor'], ['playful', 'cuddly', 'gentle'], ['silky'],
      [['eyes', 'big dark almond eyes'], ['tail', 'a plumed tail curled over the back'], ['body', 'a small, sturdy body'], ['ears', 'drop ears with long feathering'], ['muzzle', 'a short, soft muzzle']]),
    breed('west-highland-white-terrier', 'West Highland White Terrier', 'Scotland', 2, 4, 3, ['Westie', 'West'], ['westie', 'estie'],
      ['white'], ['playful', 'brave', 'mischievous'], ['wiry'],
      [['ears', 'small, pointed erect ears'], ['head', 'a round, chrysanthemum-like face of fur'], ['eyes', 'dark, piercing eyes'], ['tail', 'a carrot-shaped tail'], ['body', 'a compact, sturdy body']]),
    breed('scottish-terrier', 'Scottish Terrier', 'Scotland', 2, 3, 3, ['Scottie', 'Scot'], ['scottie', 'ottie'],
      ['black', 'brindle', 'cream'], ['brave', 'independent', 'loyal'], ['wiry'],
      [['beard', 'a distinguished long beard'], ['eyebrows', 'bushy eyebrows'], ['legs', 'short, sturdy legs'], ['ears', 'pointed erect ears'], ['body', 'a compact, low-slung body']]),
    breed('chow-chow', 'Chow Chow', 'China', 4, 2, 5, ['Chow'], ['chow', 'ow'],
      ['red', 'black', 'cream', 'grey'], ['independent', 'regal', 'calm'], ['mane', 'fluffy'],
      [['ruff', 'a dense lion-like mane'], ['tongue', 'a blue-black tongue'], ['muzzle', 'a broad, flat muzzle'], ['eyes', 'deep-set almond eyes'], ['body', 'a sturdy, square build']]),
    breed('shar-pei', 'Shar Pei', 'China', 3, 2, 1, ['Shar', 'Sharpa'], ['pei', 'arpei'],
      ['fawn', 'cream', 'black', 'red'], ['loyal', 'calm', 'independent'], ['wrinkly'],
      [['wrinkles', 'deep wrinkles and loose folds of skin'], ['muzzle', "a broad 'hippo' muzzle"], ['ears', 'tiny, triangular folded ears'], ['eyes', 'small, sunken eyes'], ['tail', 'a thick, curled tail']]),
    breed('papillon', 'Papillon', 'France', 1, 4, 4, ['Papi', 'Pap'], ['pillon', 'illon'],
      ['redWhite', 'bicolor', 'tricolor'], ['playful', 'smart', 'energetic'], ['bigEars', 'silky'],
      [['ears', 'large, fringed butterfly-wing ears'], ['body', 'a tiny, dainty body'], ['tail', 'a plumed tail arched over the back'], ['muzzle', 'a fine, pointed muzzle'], ['eyes', 'dark, round eyes']]),
    breed('irish-wolfhound', 'Irish Wolfhound', 'Ireland', 5, 3, 3, ['Wolf', 'Irish'], ['wolf', 'hound'],
      ['grey', 'brindle', 'fawn', 'cream'], ['gentle', 'calm', 'loyal'], ['wiry'],
      [['body', 'an enormously tall, lean frame'], ['head', 'a long head with a wiry beard'], ['legs', 'long, powerful legs'], ['ears', 'small, rose-shaped ears'], ['eyes', 'dark, gentle eyes']]),
    breed('vizsla', 'Vizsla', 'Hungary', 4, 5, 1, ['Viz', 'Vizs'], ['zsla', 'sla'],
      ['red'], ['cuddly', 'energetic', 'gentle'], ['sleek'],
      [['eyes', 'amber eyes that blend with the coat'], ['ears', 'long, silky drop ears'], ['body', "a lean, athletic hunter's build"], ['nose', 'a reddish-brown nose'], ['muzzle', 'a long, refined muzzle']])
  ];

  const CATS = [
    breed('siamese', 'Siamese', 'Thailand', 2, 4, 1, ['Sia', 'Siam'], ['mese', 'amese'],
      ['pointed'], ['chatty', 'cuddly', 'smart'], ['sleek', 'bigEars'],
      [['eyes', 'vivid sapphire-blue almond eyes'], ['head', 'a wedge-shaped head'], ['ears', 'large, pointed ears'], ['body', 'a long, slender, elegant body'], ['tail', 'a long, whip-thin tail']]),
    breed('persian', 'Persian', 'Iran', 3, 1, 5, ['Pers', 'Persi'], ['sian', 'ersian'],
      ['white', 'grey', 'black', 'cream', 'red', 'silver', 'calico', 'tabby'], ['calm', 'regal', 'gentle'], ['fluffy', 'mane'],
      [['muzzle', 'a flat, pushed-in face'], ['eyes', 'large, round copper eyes'], ['ears', 'small, rounded ears'], ['body', 'a cobby, stocky body'], ['tail', 'a short, bushy tail']]),
    breed('maine-coon', 'Maine Coon', 'Maine, USA', 5, 3, 5, ['Maine', 'Coon'], ['coon'],
      ['tabby', 'red', 'black', 'silver', 'white', 'tortie'], ['gentle', 'playful', 'smart'], ['fluffy', 'tufted'],
      [['ears', 'big, lynx-like tufted ears'], ['tail', 'a huge, bushy raccoon-like tail'], ['body', 'a very large, muscular body'], ['ruff', 'a shaggy lion-like ruff'], ['paws', 'big, tufted snowshoe paws']]),
    breed('bengal', 'Bengal', 'USA', 3, 5, 1, ['Ben', 'Beng'], ['gal', 'engal'],
      ['rosetted', 'silverSpotted'], ['energetic', 'wild', 'curious'], ['spotted', 'sleek'],
      [['body', 'a muscular, athletic, leopard-like build'], ['eyes', 'large, green-gold oval eyes'], ['head', 'a small, wild-looking head'], ['ears', 'short, rounded ears'], ['sheen', 'a glittery pelt that shimmers in the light']]),
    breed('sphynx', 'Sphynx', 'Canada', 3, 4, 1, ['Sphyn', 'Sphy'], ['phynx', 'ynx'],
      ['cream', 'grey', 'black', 'calico'], ['cuddly', 'playful', 'mischievous'], ['hairless', 'bigEars'],
      [['wrinkles', 'soft wrinkles on the forehead and shoulders'], ['ears', 'huge, bat-like ears'], ['eyes', 'big, lemon-shaped eyes'], ['body', 'a lean, muscular, pot-bellied body'], ['whiskers', 'few or no whiskers']]),
    breed('ragdoll', 'Ragdoll', 'USA', 4, 2, 4, ['Rag', 'Ragdo'], ['doll', 'oll'],
      ['pointed', 'mitted'], ['cuddly', 'calm', 'gentle'], ['fluffy', 'silky'],
      [['eyes', 'big, sapphire-blue eyes'], ['body', 'a large, floppy, relaxed body'], ['tail', 'a long, plumed tail'], ['ruff', 'a soft, fluffy bib'], ['head', 'a broad, soft head']]),
    breed('british-shorthair', 'British Shorthair', 'England', 4, 2, 3, ['Brit', 'Briti'], ['tish', 'ritish'],
      ['grey', 'cream', 'black', 'white'], ['calm', 'gentle', 'independent'], ['plush'],
      [['head', 'a round, chubby-cheeked face'], ['eyes', 'big, round copper eyes'], ['body', 'a stocky, cobby teddy-bear body'], ['ears', 'small, rounded ears'], ['legs', 'short, thick legs']]),
    breed('scottish-fold', 'Scottish Fold', 'Scotland', 3, 2, 3, ['Scotti', 'Scot'], ['fold', 'old'],
      ['grey', 'white', 'tabby', 'calico', 'cream'], ['cuddly', 'calm', 'curious'], ['foldEars'],
      [['ears', 'tiny, forward-folded ears'], ['head', 'a round, owl-like head'], ['eyes', 'large, round eyes'], ['body', 'a medium, rounded body'], ['tail', 'a thick, tapering tail']]),
    breed('russian-blue', 'Russian Blue', 'Russia', 3, 3, 2, ['Russ', 'Rusi'], ['sian', 'blue'],
      ['grey'], ['gentle', 'smart', 'calm'], ['plush'],
      [['eyes', 'vivid emerald-green eyes'], ['body', 'a fine-boned, graceful body'], ['mouth', "a gentle 'Mona Lisa' smile"], ['ears', 'large, pointed ears'], ['sheen', 'silver-tipped fur that shimmers']]),
    breed('abyssinian', 'Abyssinian', 'Ethiopia', 3, 5, 1, ['Aby', 'Abys'], ['ssinian', 'sinian'],
      ['ticked', 'red'], ['energetic', 'curious', 'playful'], ['sleek'],
      [['ears', 'large, alert ears'], ['eyes', 'almond-shaped gold or green eyes'], ['body', 'a lithe, athletic body'], ['head', 'a slightly rounded wedge head'], ['legs', 'long, slender legs']]),
    breed('norwegian-forest-cat', 'Norwegian Forest Cat', 'Norway', 5, 3, 5, ['Norwe', 'Norsk'], ['wegian', 'orsk'],
      ['tabby', 'white', 'black', 'silver', 'bicolor'], ['independent', 'gentle', 'curious'], ['fluffy', 'tufted'],
      [['ruff', 'a full, majestic neck ruff'], ['ears', 'lynx-tipped ears'], ['tail', 'a long, bushy tail'], ['body', 'a large, sturdy body'], ['eyes', 'large, almond-shaped eyes']]),
    breed('siberian', 'Siberian', 'Russia', 4, 4, 5, ['Sibe', 'Siber'], ['berian', 'erian'],
      ['tabby', 'silver', 'white', 'red'], ['playful', 'cuddly', 'curious'], ['fluffy'],
      [['body', 'a powerful, barrel-shaped body'], ['ruff', 'a fluffy mane'], ['tail', 'a thick, bushy tail'], ['eyes', 'large, round eyes'], ['paws', 'big, tufted paws']]),
    breed('burmese', 'Burmese', 'Myanmar', 3, 4, 1, ['Bur', 'Burm'], ['mese', 'urmese'],
      ['sable', 'chocolate', 'grey', 'cream'], ['cuddly', 'playful', 'curious'], ['sleek'],
      [['eyes', 'big, round golden eyes'], ['head', 'a rounded head'], ['body', 'a compact, surprisingly heavy body'], ['ears', 'medium, rounded ears'], ['sheen', 'a satin-like glossy sheen']]),
    breed('birman', 'Birman', 'Myanmar', 3, 2, 4, ['Bir', 'Birma'], ['man', 'rman'],
      ['pointed'], ['gentle', 'cuddly', 'calm'], ['silky'],
      [['paws', "pure white 'gloved' paws"], ['eyes', 'deep sapphire-blue eyes'], ['ruff', 'a soft neck ruff'], ['body', 'a medium, stocky body'], ['tail', 'a plumed tail']]),
    breed('devon-rex', 'Devon Rex', 'England', 2, 5, 2, ['Devon', 'Dev'], ['rex', 'evon'],
      ['grey', 'cream', 'tortie', 'black', 'white'], ['mischievous', 'playful', 'cuddly'], ['curly', 'bigEars'],
      [['ears', 'huge, low-set pixie ears'], ['eyes', 'large, oval eyes'], ['head', 'a small, elfin face'], ['body', 'a slender, lightweight body'], ['whiskers', 'short, crinkly whiskers']]),
    breed('cornish-rex', 'Cornish Rex', 'England', 2, 5, 2, ['Corni', 'Corn'], ['nish', 'rex'],
      ['black', 'white', 'red', 'tortie', 'calico'], ['energetic', 'playful', 'mischievous'], ['curly'],
      [['body', 'a slim, greyhound-like arched body'], ['ears', 'large, high-set ears'], ['head', 'an egg-shaped head'], ['legs', 'long, slender legs'], ['eyes', 'large, oval eyes']]),
    breed('oriental-shorthair', 'Oriental Shorthair', 'Thailand', 2, 5, 1, ['Orien', 'Ori'], ['ental', 'iental'],
      ['black', 'white', 'chocolate', 'grey', 'red', 'tabby'], ['chatty', 'playful', 'smart'], ['bigEars', 'sleek'],
      [['ears', 'enormous, flared ears'], ['head', 'a long, wedge-shaped head'], ['eyes', 'almond-shaped green eyes'], ['body', 'a long, svelte body'], ['tail', 'a long, thin tail']]),
    breed('american-shorthair', 'American Shorthair', 'USA', 3, 3, 2, ['Ameri', 'Amer'], ['merican', 'ican'],
      ['silver', 'tabby', 'white', 'black', 'red'], ['gentle', 'playful', 'calm'], ['sleek'],
      [['head', 'a big, round face with full cheeks'], ['body', 'a sturdy, muscular body'], ['eyes', 'large, round eyes'], ['ears', 'medium, rounded ears'], ['legs', 'strong, sturdy legs']]),
    breed('turkish-angora', 'Turkish Angora', 'Turkey', 2, 4, 4, ['Ango', 'Angor'], ['gora', 'ora'],
      ['white', 'black', 'red', 'cream'], ['playful', 'smart', 'regal'], ['silky'],
      [['eyes', 'almond eyes, sometimes odd-colored'], ['tail', 'a long, plumed tail'], ['body', 'a slender, graceful body'], ['ears', 'large, tufted ears'], ['head', 'a small, wedge-shaped head']]),
    breed('turkish-van', 'Turkish Van', 'Turkey', 4, 5, 3, ['Van', 'Vanni'], ['van'],
      ['van'], ['energetic', 'playful', 'independent'], ['silky'],
      [['eyes', 'amber or odd-colored eyes'], ['body', "a long, muscular swimmer's body"], ['tail', 'a bushy, ringed tail'], ['ears', 'large, well-furred ears'], ['legs', 'strong, sturdy legs']]),
    breed('savannah', 'Savannah', 'USA', 5, 5, 1, ['Sava', 'Savan'], ['vannah', 'annah'],
      ['leopard', 'silverSpotted'], ['wild', 'energetic', 'curious'], ['spotted', 'bigEars'],
      [['ears', 'huge, tall ears'], ['legs', 'very long legs'], ['body', 'a tall, lean, serval-like body'], ['eyes', 'hooded eyes with dark tear-stripe markings'], ['neck', 'a long neck']]),
    breed('manx', 'Manx', 'Isle of Man', 3, 3, 2, ['Man', 'Manxi'], ['manx', 'anx'],
      ['tabby', 'black', 'calico', 'tortie', 'white'], ['playful', 'loyal', 'curious'], ['bobtail'],
      [['tail', 'no tail at all, just a rounded rump'], ['legs', 'longer hind legs that give a rabbit-like hop'], ['head', 'a round head with full cheeks'], ['body', 'a compact, round body'], ['eyes', 'big, round eyes']]),
    breed('egyptian-mau', 'Egyptian Mau', 'Egypt', 3, 5, 1, ['Mau', 'Egyp'], ['mau', 'au'],
      ['silverSpotted', 'leopard'], ['energetic', 'loyal', 'playful'], ['spotted', 'speedy'],
      [['eyes', 'gooseberry-green eyes'], ['forehead', "a scarab-like 'M' marking on the forehead"], ['body', 'a graceful, muscular body'], ['legs', 'long hind legs built for speed'], ['ears', 'medium, alert ears']]),
    breed('balinese', 'Balinese', 'USA', 2, 4, 4, ['Bali', 'Balin'], ['linese', 'nese'],
      ['pointed'], ['chatty', 'playful', 'cuddly'], ['silky'],
      [['eyes', 'deep blue almond eyes'], ['tail', 'a graceful, plumed tail'], ['head', 'a wedge-shaped head'], ['body', 'a slender, elegant body'], ['ears', 'large, pointed ears']]),
    breed('chartreux', 'Chartreux', 'France', 4, 3, 3, ['Char', 'Chartr'], ['treux', 'reux'],
      ['grey'], ['calm', 'loyal', 'gentle'], ['plush'],
      [['eyes', 'copper-orange eyes'], ['mouth', 'a sweet, smiling expression'], ['body', "a robust 'potato on toothpicks' body"], ['legs', 'fine, slender legs'], ['head', 'a round head with full cheeks']]),
    breed('selkirk-rex', 'Selkirk Rex', 'USA', 4, 2, 4, ['Selk', 'Sel'], ['kirk', 'irk'],
      ['grey', 'white', 'calico', 'cream', 'tabby'], ['cuddly', 'calm', 'playful'], ['curly'],
      [['head', 'a round head'], ['eyes', 'large, round eyes'], ['body', 'a heavy-boned, sturdy body'], ['whiskers', 'curly whiskers'], ['tail', 'a thick, curly tail']]),
    breed('munchkin', 'Munchkin', 'USA', 2, 4, 2, ['Munch', 'Munchk'], ['kin', 'chkin'],
      ['tabby', 'black', 'white', 'calico', 'red'], ['playful', 'curious', 'cuddly'], ['shortLegs'],
      [['legs', 'extra-short little legs'], ['body', 'a normal-length body on tiny legs'], ['eyes', 'walnut-shaped eyes'], ['head', 'a rounded wedge head'], ['tail', 'a tail held high']]),
    breed('somali', 'Somali', 'USA', 3, 5, 4, ['Soma', 'Som'], ['mali', 'ali'],
      ['ticked', 'red'], ['energetic', 'playful', 'mischievous'], ['fluffy', 'tufted'],
      [['tail', 'a big, fox-like bushy tail'], ['ears', 'large, tufted ears'], ['eyes', 'almond-shaped gold or green eyes'], ['ruff', 'a full ruff and britches'], ['body', 'a lithe, medium body']]),
    breed('japanese-bobtail', 'Japanese Bobtail', 'Japan', 2, 5, 2, ['Bob', 'Bobta'], ['tail', 'bob'],
      ['calico', 'bicolor', 'white'], ['playful', 'chatty', 'curious'], ['bobtail'],
      [['tail', 'a short, pom-pom bunny tail'], ['body', 'a lean, muscular body'], ['eyes', 'large, oval eyes'], ['ears', 'large, upright ears'], ['legs', 'long hind legs']]),
    breed('laperm', 'LaPerm', 'USA', 2, 3, 3, ['LaPer', 'Lap'], ['perm', 'erm'],
      ['tabby', 'red', 'cream', 'calico', 'tortie'], ['cuddly', 'curious', 'playful'], ['curly'],
      [['ruff', 'a curly neck ruff'], ['ears', 'slightly flared, tufted ears'], ['eyes', 'expressive almond eyes'], ['tail', 'a curly plumed tail'], ['body', 'a medium, graceful body']])
  ];

  // Real-world names for crosses that already exist. Order within a pair does not matter.
  const KNOWN_CROSSES = {
    dog: [
      ['labrador-retriever', 'poodle', 'Labradoodle'],
      ['golden-retriever', 'poodle', 'Goldendoodle'],
      ['golden-retriever', 'labrador-retriever', 'Goldador'],
      ['cocker-spaniel', 'poodle', 'Cockapoo'],
      ['cavalier-king-charles-spaniel', 'poodle', 'Cavapoo'],
      ['maltese', 'poodle', 'Maltipoo'],
      ['yorkshire-terrier', 'poodle', 'Yorkipoo'],
      ['miniature-schnauzer', 'poodle', 'Schnoodle'],
      ['bernese-mountain-dog', 'poodle', 'Bernedoodle'],
      ['australian-shepherd', 'poodle', 'Aussiedoodle'],
      ['old-english-sheepdog', 'poodle', 'Sheepadoodle'],
      ['shih-tzu', 'poodle', 'Shih-Poo'],
      ['border-collie', 'poodle', 'Bordoodle'],
      ['jack-russell-terrier', 'poodle', 'Jackapoo'],
      ['dachshund', 'poodle', 'Doxiepoo'],
      ['havanese', 'poodle', 'Havapoo'],
      ['west-highland-white-terrier', 'poodle', 'Westiepoo'],
      ['saint-bernard', 'poodle', 'Saint Berdoodle'],
      ['german-shepherd', 'poodle', 'Shepadoodle'],
      ['rottweiler', 'poodle', 'Rottle'],
      ['dalmatian', 'poodle', 'Dalmadoodle'],
      ['doberman-pinscher', 'poodle', 'Doberdoodle'],
      ['newfoundland', 'poodle', 'Newfypoo'],
      ['pembroke-welsh-corgi', 'poodle', 'Corgipoo'],
      ['chihuahua', 'poodle', 'Chipoo'],
      ['pomeranian', 'poodle', 'Pomapoo'],
      ['bichon-frise', 'poodle', 'Poochon'],
      ['pug', 'beagle', 'Puggle'],
      ['pomeranian', 'siberian-husky', 'Pomsky'],
      ['chihuahua', 'dachshund', 'Chiweenie'],
      ['german-shepherd', 'siberian-husky', 'Gerberian Shepsky'],
      ['siberian-husky', 'pembroke-welsh-corgi', 'Horgi'],
      ['french-bulldog', 'boston-terrier', 'Frenchton'],
      ['maltese', 'yorkshire-terrier', 'Morkie'],
      ['shih-tzu', 'yorkshire-terrier', 'Shorkie'],
      ['cavalier-king-charles-spaniel', 'bichon-frise', 'Cavachon'],
      ['shih-tzu', 'bichon-frise', 'Zuchon'],
      ['chihuahua', 'yorkshire-terrier', 'Chorkie'],
      ['pomeranian', 'chihuahua', 'Pomchi'],
      ['labrador-retriever', 'siberian-husky', 'Labsky'],
      ['golden-retriever', 'siberian-husky', 'Goberian'],
      ['beagle', 'labrador-retriever', 'Beagador'],
      ['pembroke-welsh-corgi', 'labrador-retriever', 'Corgidor'],
      ['boxer', 'labrador-retriever', 'Boxador'],
      ['german-shepherd', 'labrador-retriever', 'Sheprador'],
      ['pug', 'chihuahua', 'Chug'],
      ['boston-terrier', 'pug', 'Bugg'],
      ['maltese', 'shih-tzu', 'Mal-Shi'],
      ['bulldog', 'beagle', 'Beabull'],
      ['alaskan-malamute', 'siberian-husky', 'Alusky'],
      ['samoyed', 'siberian-husky', 'Samusky'],
      ['basset-hound', 'beagle', 'Bagle Hound'],
      ['pug', 'shar-pei', 'Ori-Pei'],
      ['beagle', 'dachshund', 'Doxle'],
      ['pug', 'french-bulldog', 'Frug'],
      ['pembroke-welsh-corgi', 'dachshund', 'Dorgi'],
      ['chihuahua', 'jack-russell-terrier', 'Jack Chi'],
      ['beagle', 'jack-russell-terrier', 'Jackabee'],
      ['siberian-husky', 'pug', 'Hug'],
      ['shih-tzu', 'pug', 'Pug-Zu'],
      ['siberian-husky', 'rottweiler', 'Rottsky'],
      ['pembroke-welsh-corgi', 'german-shepherd', 'Corman Shepherd']
    ],
    cat: [
      ['persian', 'siamese', 'Himalayan'],
      ['siamese', 'burmese', 'Tonkinese'],
      ['siamese', 'abyssinian', 'Ocicat'],
      ['persian', 'american-shorthair', 'Exotic Shorthair'],
      ['siamese', 'american-shorthair', 'Snowshoe'],
      ['persian', 'burmese', 'Burmilla'],
      ['burmese', 'american-shorthair', 'Bombay'],
      ['sphynx', 'munchkin', 'Bambino'],
      ['persian', 'munchkin', 'Minuet'],
      ['scottish-fold', 'munchkin', 'Scottish Kilt'],
      ['laperm', 'munchkin', 'Skookum'],
      ['selkirk-rex', 'munchkin', 'Lambkin']
    ]
  };

  return {
    SPECIES,
    COLORS,
    TEMPERAMENTS,
    LOOK_TAGS,
    COLOR_NAMES,
    ORIGIN_NAMES,
    SIZE_NAMES,
    FLOOF_LABELS,
    BREEDS: { dog: DOGS, cat: CATS },
    KNOWN_CROSSES
  };
});
